### ISSUE TITLE
'ffmpeg batch' closes while processing 'join files'

### ISSUE THREAD

**Issue by gerb0n** [eibol/ffmpeg_batch#10]
Is it expected behavior that the program closes when you do a 'join files' action?
Afer that the ffmpeg-cli will do it's job in the background but it leaves you with no feedback about the progress.

Not sure if you can do anything about this because you would need a way to retrieve the progress of ffmpeg.

**Comment by eibol** [comment]
Hi, join files should show progress information. I would need more information, or sample files to test this issue;
- In settings, is "Use concat filter" enabled?
- What encoding parameters are you using? Are you re-encoding or stream copying?

**Comment by gerb0n** [comment]
'Use concat video filter for joining files' is disabled.
The encoding parameters I use are  **-c copy**

I am not bound to those parameters; if you suggest other parameters to join the files at highest quality (or close to it) that's okay too.

My usecase is that I am joining around 16k jpegs. The first minute or so I see some progress information ub the form of 'time elapsed'. No percentage or anything. After that the program closes and ffmpeg continues in the background.

**Comment by eibol** [comment]
Hi, image concatenation is not supported yet, it requires some modification of the join files feature.
I'll take note for the next release.
