### ISSUE TITLE
Feature request Save pre input parameters in presets

### ISSUE THREAD

**Issue by c0dn** [eibol/ffmpeg_batch#100]
Hi, I'm transcoding using Nvidia GPUs. I use the CUDA scale filter to do full hardware transcoding, Converting H265 to AV1 limiting resolution to 1080p.

The filter requires 

`-hwaccel cuda -hwaccel_output_format cuda`

before the input file to work.

Is it possible to save pre input options in the presets and apply them on a per file basis in the queue?

**Comment by eibol** [comment]
Hi, right now it is only posible to set main parameters for individual queue files, I'll see to implement it for next release.

**Comment by eibol** [comment]
You could try this beta with such feature (replace your current executable).
[FFBatch.zip](https://github.com/eibol/ffmpeg_batch/files/14212615/FFBatch.zip)

**Comment by c0dn** [comment]
Hi, the beta build you provide works well
