### ISSUE TITLE
Can't add a file to list

### ISSUE THREAD

**Issue by Erudition** [eibol/ffmpeg_batch#101]
I'm using the Linux build optimized for wine, acquired through the website -> Sourceforge. The same issue occurs with the other builds, not optimized for wine, including the latest release on Github.

I hit add file, select a webm file, and submit. The window flashes for a split second, but no file is added to the list.

[ffmpeg_batch_bug.webm](https://github.com/eibol/ffmpeg_batch/assets/3915447/bf0fafce-b489-4a02-a0df-a757025780b0)

**Comment by eibol** [comment]
Hi, I'm afraid linux wine version is no longer supported. What operating system are you using?

**Comment by Erudition** [comment]
My distro is [Guix](https://guix.gnu.org/).

**Comment by eibol** [comment]
Hi, I could finally make it work and add files by using wine mono 9.3 in Debian 12, after installing wine and wine-mono
 I also installed q4wine, but not sure it had something to do with it (apt-install q4wine)

Download: https://dl.winehq.org/wine/wine-mono/9.3.0/wine-mono-9.3.0-x86.msi
Run: wine wine-mono-9.3.0-x86.msi

However only basic batch encoding works.
If you can make it work with this, I would give it a thought.
![ff27_1](https://github.com/user-attachments/assets/00e299bc-b650-476a-9541-488b4e767f39)
![ff27_2](https://github.com/user-attachments/assets/5d6e593d-841f-4ae6-a71a-c95982ee91ef)

**Comment by pszemus** [comment]
I've installed wine-mono-9.3.0:
![image](https://github.com/user-attachments/assets/67c7aded-e9cd-4201-b1da-15c0d78691b2)
But adding files still does not work (I can select files from "Add files" dialog, but none of them appear in the main window then). I'm using the latest version of FFmpeg Batch AV Converter Portable:
![image](https://github.com/user-attachments/assets/a11aebff-7090-4a1b-b906-00980646a360)

**Comment by eibol** [comment]
Hi, please use [this version](https://sourceforge.net/projects/ffmpeg-batch/files/FFBatch_2.3.1_Linux_Wine.zip/download), it is the only one that works in Linux for the moment.

**Comment by eibol** [comment]
This [latest beta version 3.1.2](https://drive.upm.es/s/F06X5BkCRGMIqma/download) should work better, with less constraints under wine/mono.

**Comment by eibol** [comment]
This [latest beta version 3.1.2](https://drive.upm.es/s/MNa34IKY5i6B3R4/download) should work better, with less constraints under wine/mono.

**Comment by pszemus** [comment]
@eibol Now it works really well! Thank you!
![image](https://github.com/user-attachments/assets/24b2c879-42c0-41a3-96bb-0ddc44f85f12)

**Comment by eibol** [comment]
Great. In order to avoid some errors and improve layout, I recommend to run winecfg and set as Windows 10 (Application tab), and maybe also disable themes for the application (Desktop integration tab).

![imagen](https://github.com/user-attachments/assets/1d1489b3-c40c-41b2-9f44-b3467cc2decf)
![imagen](https://github.com/user-attachments/assets/3f314333-decf-4dc4-98e5-4a58617a5339)

**Comment by eibol** [comment]
Some minor corrections in this [patched version](https://drive.upm.es/s/RaQK85WcufikCzy/download).
