### ISSUE TITLE
Can't convert to OPUS [extension not recognised]

### ISSUE THREAD

**Issue by YuriKharkov** [eibol/ffmpeg_batch#102]
I can't convert my FLAC files to OPUS.
Error log: 
[AVFormatContext @ 0000024ab7e22840] Unable to choose an output format for 'ffmpeg'; use a standard extension for the filename or specify the format manually.
[out#0 @ 0000024ab7e214c0] Error initializing the muxer for ffmpeg: Invalid argument
Error opening output file ffmpeg.
Error opening output files: Invalid argument

Encoding test failed. CHECK OUTPUT ABOVE
![image](https://github.com/eibol/ffmpeg_batch/assets/165895387/4de9b636-0d81-4145-8d6b-01fc8ceda828)

**Comment by eibol** [comment]
Hi, you don't have to add ffmpeg to parameters field, it is automaticallt included. Just include the encoding parameters.

**Comment by YuriKharkov** [comment]
> Hi, you don't have to add ffmpeg to parameters field, it is automaticallt included. Just include the encoding parameters.

Still not working, says "unable to choose output format

![image](https://github.com/eibol/ffmpeg_batch/assets/165895387/4af7f5c9-e2db-43fa-a541-76318fec7dc6)

**Comment by YuriKharkov** [comment]
Do I have to install libopus separately?

**Comment by eibol** [comment]
You should not install anything else. I'm unable to reproduce the issue, I can convert to opus trouble free.
Have you tried creating an audio preset using the wizard?
![imagen](https://github.com/eibol/ffmpeg_batch/assets/907799/021886c3-fc61-4716-b222-3eec768db790)

**Comment by YuriKharkov** [comment]
> You should not install anything else. I'm unable to reproduce the issue, I can convert to opus trouble free. Have you tried creating an audio preset using the wizard? ![imagen](https://private-user-images.githubusercontent.com/907799/321129527-021886c3-fc61-4716-b222-3eec768db790.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NDY1NjMsIm5iZiI6MTcxMjg0NjI2MywicGF0aCI6Ii85MDc3OTkvMzIxMTI5NTI3LTAyMTg4NmMzLWZjNjEtNDcxNi1iMjIyLTNlZWM3NjhkYjc5MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMVQxNDM3NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNDBkZWVkZWU3N2VhMzE1MjY4ZTEzNDQ1ZjA0ODM2MmJjZDQ2NDJkYzAyZjE5NTQ5ZDAyNTkxNmI1YjdkN2FkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7R7sStoAwU5hq6KdTZdmGA73Rx0LEt4S0EvqEKXcQyo)

i fixed the issue, it was an ffmpeg problem, had to install ffmpeg from software, rather than externally dowanloading it and adding it to system path.

**Comment by eibol** [comment]
I'm afraid application expects ffmpeg.exe in application path, nowhere else.
