### ISSUE TITLE
feature request: allow sorting by file creation/modification times, other sort options

### ISSUE THREAD

**Issue by jjsmcneil1113** [eibol/ffmpeg_batch#103]
trying to join/concat 100s files, with integers in the filenames, but are not zero padded. I request either or both features:

1) sort by creation or modification time, currently this is not an option in columns
2) allow sorting integer portion of  filename as if they were 0 padded, for example, file9.txt  and file10.txt are sorted as if they were file09.txt and file10.txt

thank you!

**Comment by jjsmcneil1113** [comment]
also request ability to concat/join audio files that have different sampling rates, bitrates (I understand this would involve re-encoding)

**Comment by eibol** [comment]
> also request ability to concat/join audio files that have different sampling rates, bitrates (I understand this would involve re-encoding)

I think you could already concat files re-encoding audio, just uncheck "Stream copy" when using native concatenation, and then use -c:v copy to stream video and the audio parameters of your choice.

**Comment by eibol** [comment]
> trying to join/concat 100s files, with integers in the filenames, but are not zero padded. I request either or both features:
> 
>     1. sort by creation or modification time, currently this is not an option in columns
> 
>     2. allow sorting integer portion of  filename as if they were 0 padded, for example, file9.txt  and file10.txt are sorted as if they were file09.txt and file10.txt
> 
> 
> thank you!

I'll look into modification date sorting.

**Comment by eibol** [comment]
[Beta release](https://drive.upm.es/s/R7cNVsyHZo0oiQT/download)

**Comment by jjsmcneil1113** [comment]
THANK YOU!!!!
