### ISSUE TITLE
Audio Codec info is gone on 3.0.6

### ISSUE THREAD

**Issue by johnloopi** [eibol/ffmpeg_batch#108]
I've had 3.0.5 since it was released but since "Version 3.0.6 availible" has been there for a while now, I thought I'd better update.
The Audio Codec info that used to be on 3.0.5 is now gone for me on 3.0.6. Has anyone else experienced this?

3.0.5:
![3 0 5](https://github.com/eibol/ffmpeg_batch/assets/147723143/a1f1ddba-112e-4f3c-acca-b6f1138bb3cb)

3.0.6:

![3 0 6](https://github.com/eibol/ffmpeg_batch/assets/147723143/34f9ba07-14eb-4566-9157-adb4ea978e93)

You might notice that this is the portable version, but it occurs on the regular installed version as well, it was just easier to have both like this to easy switch to both versions when screenshotting.

**Comment by eibol** [comment]
Hi, could you please send a sample file causing this issue?
I updated mediainfo.exe, and also added a new custom column, it may have caused this problem.
Thanks

**Comment by eibol** [comment]
This [patched version](https://drive.upm.es/s/R7cNVsyHZo0oiQT/download) may solve the issue.

**Comment by eibol** [comment]
Great,. I guess it is no longer necessary to test a sample file.
Cheers
