### ISSUE TITLE
Question / Feature Request - Does this support volume analysis / normalization?

### ISSUE THREAD

**Issue by IlIiIlIIlIiIlIlIIIlI** [eibol/ffmpeg_batch#109]
Hi, looking to find a front end for ffmpeg that assists with volume anaylsis / and normalization of the audio track without re-encoding the video? Would this do the job?

Currently handling via powershell, but its taking forever just to analyze the movie's volume level and doesn't give any kind of progress indications in my basic script.

Thanks

**Comment by eibol** [comment]
Hi, do you mean something like https://superuser.com/questions/323119/how-can-i-normalize-audio-using-ffmpeg

**Comment by IlIiIlIIlIiIlIlIIIlI** [comment]
> Hi, do you mean something like https://superuser.com/questions/323119/how-can-i-normalize-audio-using-ffmpeg

Yeah, I was able to do it via a powershell script I made, but it would be really nice if this application could do it instead and I could queue items up.

**Comment by eibol** [comment]
Which are the ffmpeg parameters you are using for normalization in your script?

**Comment by IlIiIlIIlIiIlIlIIIlI** [comment]
This is what I used, took a few attempts, but it made the movie I was trying to watch louder / normalized like I wanted. I may be doing it wrong, but it seemed to work:

# Normalize the audio and save the new file
Write-Host "Normalizing the audio. This may take a few minutes..."
Start-Process -NoNewWindow -Wait -FilePath $ffmpegPath -ArgumentList "-i `"$mkvFilePath`" -vcodec copy -acodec aac -b:a 320k -af loudnorm=I=-16:TP=-1.5:LRA=11 `"$outputFilePath`""

**Comment by eibol** [comment]
I've found no problem using those parameters in FFBatch. Just use in parameters field:

`-vcodec copy -acodec aac -b:a 320k -af loudnorm=I=-16:TP=-1.5:LRA=11`

Leave format blank (or set to mkv).

![imagen](https://github.com/eibol/ffmpeg_batch/assets/907799/c871a8d3-caaf-4809-ac28-0fd49b391a06)

**Comment by IlIiIlIIlIiIlIlIIIlI** [comment]
Thank you!!
