### ISSUE TITLE
Adding M3U8 links from file validating stuck

### ISSUE THREAD

**Issue by wes1993** [eibol/ffmpeg_batch#11]
Hello,
I love you software, i have found a bug, when i try to add a file with a list of M3U8 link the software stuck on validating:

![image](https://user-images.githubusercontent.com/52070589/109839011-fd0d6300-7c46-11eb-9767-3bf2f0d84bbb.png)

I have attached a screen

Best Regards
Stefano

**Comment by eibol** [comment]
Hi, thanks for the input.  
How are you adding the links, via text file? Pasting from the clipboard? Maybe the program gets stuck if one link is down.
May I have a sample link/links?

**Comment by wes1993** [comment]
Hello @eibol,
Thanks a lot for your reply!! :)
I’m trying to add via a TXT file created by notepad, give me 15 minutes and I will attach the file here :)

**Comment by wes1993** [comment]
P.S. the links are all online and If I add one link per time the validating finish without any problem :)

**Comment by wes1993** [comment]
This is the file
[Attrazione Fatale S01.txt](https://github.com/eibol/ffmpeg_batch/files/6078644/Attrazione.Fatale.S01.txt)

**Comment by eibol** [comment]
Ok, I think I found the issue, I will generate a beta executable for you to test soon.

**Comment by wes1993** [comment]
Thanks a lot @eibol!!!
Really thanks a lot for your help and your support :-D
Best Regards
Stefano

**Comment by eibol** [comment]
You can try this [beta executable](https://drive.upm.es/index.php/s/CXk3IFV0TRTbwf2)

**Comment by wes1993** [comment]
Perfecttttttt!!!! Thanksssss a lot!! :-D
Now Works really well!!
I love your program!!
Stefano
