### ISSUE TITLE
Checksum warning after recent install v3.0.7

### ISSUE THREAD

**Issue by kvanderhaeghen-aleacsysonline** [eibol/ffmpeg_batch#111]
There seems to be an issue with the latest 3.0.7 version. It seems that it forgot to override the ffmpeg.exe? I got a warning that it didn't know the checksum of that exe.
![image](https://github.com/eibol/ffmpeg_batch/assets/102219857/5cbf0e9b-2d65-4a6a-9613-af25794952a1)

![image](https://github.com/eibol/ffmpeg_batch/assets/102219857/ebb19f29-1ec3-4863-a4f5-8e792670284e)

**Comment by eibol** [comment]
Hi, it is not an issue, If you don't want to see these messages, just trust ffmpeg and then check "Do not validate ffmpeg".
Anyway, you can download latest [ffmpeg 7.0.1](https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-full.7z), it should not warn you.

**Comment by kvanderhaeghen-aleacsysonline** [comment]
Ok I understand, but is it possible that the installer overwrites the ffmpeg.exe with the new one? Or isn't that possible to implement in the installer? I'm just wondering 😄

**Comment by eibol** [comment]
> Ok I understand, but is it possible that the installer overwrites the ffmpeg.exe with the new one? Or isn't that possible to implement in the installer? I'm just wondering 😄

The installer always overwrites ffmpeg.exe, so the warning will display if an updated ffmpeg executable is included.
The valid checksum is the one of the new ffmpeg 7.0.1 essential.

Anyway, it is becoming somewhat a hassle, so I included the settings to disable it for good.

**Comment by kvanderhaeghen-aleacsysonline** [comment]
Ow okay, I thought it checked if I was using the new one and thought the exe still was the old one and the hash didn't match because of it. My bad, I will accept the message then 👍
