### ISSUE TITLE
Discrete graphics card not recognized

### ISSUE THREAD

**Issue by Nvertd** [eibol/ffmpeg_batch#112]
The program does not recognize my discrete graphics card (RTX 3050 on a laptop), i have set windows graphics settings for the app to use the nvidia graphics. But the app only recognizes the intel one.

**Comment by eibol** [comment]
Hi, can you include any error message, screenshot, log file.
Thanks

**Comment by Nvertd** [comment]
![image](https://github.com/eibol/ffmpeg_batch/assets/162870405/50b2f3f4-3628-40a0-97e7-1843c93689fc)
![image](https://github.com/eibol/ffmpeg_batch/assets/162870405/dd56e68e-3591-4676-8cd0-e55c06057db0)
The RTX gpu is available to the app, but the app chooses the intel uhd graphics

**Comment by eibol** [comment]
That windows displays just basic system information, it does not mead the video card is not available for encoding.
just try nvidia encoders (h264_nvenc/hevc_nvenc), or use the preset wizard.
