### ISSUE TITLE
FFmpeg Batch 无法使用 -vf subtitles 添加字幕

### ISSUE THREAD

**Issue by Soizzer** [eibol/ffmpeg_batch#113]
操作系统：Windows 10 专业工作站版 19044.1320
显卡：NVIDIA GeForce GTX 1050 Ti

使用参数：-c:v hevc_nvenc -vf subtitles=00.srt -b:v 1500K  -c:a copy

报错提示：
Unable to open 00.srt
Error initializing filters
Error initializing a simple filtergraph

报错如图：

![01](https://github.com/user-attachments/assets/6415f880-9f15-4ff2-b05f-82a9a8ce09a1)
![02](https://github.com/user-attachments/assets/71109a1e-d79c-4347-b2c2-fdc05014175d)

**Comment by eibol** [comment]
Hello, it looks like a problem with "Try preset" feature.
Please try disabling it before encoding.

I'm aware of the limitations of the application, but I have no resources since it is a free program with little support from others.
