### ISSUE TITLE
Custom preset fails if it contains codec name

### ISSUE THREAD

**Issue by NIKENIT** [eibol/ffmpeg_batch#114]
If you try to add a custom encoding preset to any file, and the preset line contains a codec name, it always crashes the encoding.

For example, the valid line
`-c:v libx264 -crf 18 -vf scale=-2:720 -c:a copy -preset veryslow`
always fails with the error 
`Unknown encoder 'lib'`

Or you can just test it on the default "presets" that come with the program, most of them will also fail. 

The same line works perfectly if used in the base parameters window.

**Comment by eibol** [comment]
I can't reproduce this issue, could you send some screenshots for further investigation?

**Comment by NIKENIT** [comment]
Hi. Basically add the "Encoding parameters" column, go to the "Set custom preset" for the file, and select any default template that contains a codec name, for example "Video: Resize 1280x720 H264-AAC". Then press "Sequential encoding", and it will crash.

Just reproduced it, 

![image](https://github.com/user-attachments/assets/29b92352-05b5-4641-baeb-0571fc31192f)
![image](https://github.com/user-attachments/assets/67d93e9a-d898-44be-952a-a2b42eb3bbaf)
![image](https://github.com/user-attachments/assets/f9355ce1-d073-4873-8041-8cbd1b8a278a)

**Comment by eibol** [comment]
Hi, I now understand the possible bug, thanks for the report.
I'll check it asap.

**Comment by eibol** [comment]
Can you try this patched version? Issue should now be fixed.
[](https://drive.upm.es/s/R7cNVsyHZo0oiQT/download)
