### ISSUE TITLE
Possible frame count off by 100 in "Get total Seconds/frames" context menu feature?

### ISSUE THREAD

**Issue by carco5a** [eibol/ffmpeg_batch#115]
FFmpeg Batch V 3.0.7

My steps to reproduce:
1. Load in a MP4 file (AVC, H.264) that is 30fps and 2870 total seconds
2. Select file, right click -> "Get total Seconds/frames"

Result: 
Total frames reported is ~861 frames 

![image](https://github.com/user-attachments/assets/6d4fbc67-c232-478e-886e-48ef4b1a29f3)

Expected Result:
~86,100 frames (2870 * 30)

If you take the same file and perform: 
`ffprobe -v error -select_streams v:0 -show_entries stream=nb_frames -of default=nokey=1:noprint_wrappers=1 FILE.mp4`
it returns: 86100

Is the frame count reported by FFmpeg Batch off by 100?

I started to read over:
https://github.com/eibol/ffmpeg_batch/blob/master/FFBatch/Form28.cs#L91 and MediaInfo.exe usage but then my pup had to poop so I'm not sure where the issue it as of yet.

**Comment by eibol** [comment]
Hi, thanks for the report. probably it is a bug due to localization.
I'll look into it.

**Comment by eibol** [comment]
Can you try this patched version?
[FFBatch_patched_308](https://drive.upm.es/s/R7cNVsyHZo0oiQT/download)

**Comment by carco5a** [comment]
I tried this new exe on top of an existing 307 install and it appears to be reporting the correct frames now. Thanks for taking a look!
![image](https://github.com/user-attachments/assets/f758349d-16ca-4455-8638-a7a32ff92c0c)

**Comment by eibol** [comment]
Great.
