### ISSUE TITLE
ERROR: Cannot download embed-only video without embedding URL. Please call youtube-dl with the URL of the page that embeds this video.

### ISSUE THREAD

**Issue by fixck** [eibol/ffmpeg_batch#119]
Hi,

 I got the error in the title and found this solution but I'm not sure how to apply it to 
 FFmpeg Batch AV Converter
 
 https://www.reddit.com/r/youtubedl/comments/lbrb2y/downloading_embedded_vimeo_videos/
 
 I checked these urls on the vimeo developer page:
 
 div id = "player"
class = "player" > < /div> <
script > window.playerConfig = {
        "cdn_url": "https://f.vimeocdn.com",
        "vimeo_api_url": "api.vimeo.com",
        "request": {
            "files": {
                "dash": {
                    "cdns": {
                        "akfire_interconnect_quic": {
                            "avc_url": "https://vod-adaptive-ak.vimeocdn.com//XXX/XXX/playlist/av/primary/playlist.json?omit=av1-hevc\u0026pathsig=8c953e4f~A_qXXXXa6FCYrxHw5Wb8XXXXM6KywP0b64Ytek\u0026qsr=1\u0026rh=3mtmPa",
                            "origin": "gcs",
                            "url": "https://vod-adaptive-ak.vimeocdn.com//XXX/XXX/v2/playlist/av/primary/playlist.json?pathsig=8c953e4f~A_A_qXXXXa6FCYrxHw5Wb8XXXXMM6KywP0b64Ytek\u0026qsr=1\u0026rh=3mtmPa"
                        },
                        "fastly_skyfire": {
                            "avc_url": "https://skyfire.vimeocdn.com/XXX/XXX/v2/playlist/av/primary/playlist.json?omit=av1-hevc\u0026pathsig=8c953e4f~A_A_qXXXXa6FCYrxHw5Wb8XXXX8b0WpGPMM6KywP0b64Ytek\u0026qsr=1\u0026rh=3mtmPa",
                            "origin": "gcs",
                            "url": "https://skyfire.vimeocdn.com//XXX/XXX/v2/playlist/av/primary/playlist.json?pathsig=8c953e4f~A_qXXXXa6FCYrxHw5Wb8XXXXYtek\u0026qsr=1\u0026rh=3mtmPa"
                        }
                    },

**Comment by eibol** [comment]
I'm not sure either. I would need a sample url displaying the error for testing.

**Comment by fixck** [comment]
> I'm not sure either. I would need a sample url displaying the error for testing.

Here's one:
[embeded-only video](https://ibb.co/rtzjt7s)

**Comment by eibol** [comment]
That is a vimeo url, not a YouTube url, you cannot use that download dialog.
You could try at main tab, pasting url.

In addition, the url displays a privacy error at browser:

![imagen](https://github.com/user-attachments/assets/86199bcd-9998-45bf-89ee-ac8629df6bef)

https://help.vimeo.com/hc/en-us/articles/12426181728273-Set-your-video-s-viewing-privacy-before-uploading
