### ISSUE TITLE
Not an issue but an enhancement

### ISSUE THREAD

**Issue by wes1993** [eibol/ffmpeg_batch#12]
Hello Again Eibol,
Thanks a lot for your beautiful work!!! Really!!
I havew another question, is there a way, when i add a list of link, to rename only the first and the the program will do all the rest?
Example:
S01E01 - I write this to the first link of the list
S02E02 - The program rename the second
S02E03 - The program rename the Third ecc

And also:
S01E13 - I write this to the first link of the list
S02E14 - The program rename the second
S02E15 - The program rename the Third ecc

Thanks a lot for your work!! Really!!
Best Regards
Stefano

**Comment by eibol** [comment]
Hi, I understand your requirement, maybe it will be available for next release.
Very busy at this moment.
Cheers

**Comment by wes1993** [comment]
Yes, no problem, when you can :-D

**Comment by eibol** [comment]
Included in latest version.

**Comment by wes1993** [comment]
Perfect!! Thanks a lot!! :)
