### ISSUE TITLE
支持无损压缩视频功能

### ISSUE THREAD

**Issue by SONGjiemo** [eibol/ffmpeg_batch#121]
支持无损压缩视频功能

**Comment by eibol** [comment]
Hi, all lossless encoding supported by ffmpeg is supported in the application.
It depends on your needs, there are ways to lossless encode video but size is usually huge and playback
compability limited. 

For example: -vcodec rawvideo -pix_fmt rgb24

**Comment by SONGjiemo** [comment]
> Hi, all lossless encoding supported by ffmpeg is supported in the application. It depends on your needs, there are ways to lossless encode video but size is usually huge and playback compability limited.
> 
> For example: -vcodec rawvideo -pix_fmt rgb24 Or HEVC (x265) -c:v libx265 -crf 0 -x265-params lossless=1

能否直接 添加一个  “无损压缩”   功能按钮

**Comment by eibol** [comment]
There's no such button, you could save lossless presets, and also save a lossless preset of your choice as the default, so it would be used when pressing sequential encoding button.
