### ISSUE TITLE
overlapping text

### ISSUE THREAD

**Issue by temis01** [eibol/ffmpeg_batch#124]
cf pic (same with english lang interface)
<img width="962" alt="overlapping tags" src="https://github.com/user-attachments/assets/8e3d2645-63fe-49d8-a1bc-b5dfb3ef47d6">

**Comment by eibol** [comment]
Hi, I found an issue with screen scaling factor, tha hapens when desktop scaling is higher than 100%.
I'm checking how to solve it. Apologize for the inconvenience.

**Comment by temis01** [comment]
Totally makes sense pic above is 150% on 4K monitor
This pic is 100%
also if it's possible to make sure that the label of some options and functions (bottom right) are completely visible.
It's ok with the english lang interface but not in french.
Other than that nice work for this thorough FFMPEG GUI ;)
![overlapping tags 100%](https://github.com/user-attachments/assets/a9e49539-4c98-49a7-8a6d-86448ea10223)

**Comment by eibol** [comment]
Hi, could you try this [patched 3.1.0 version](https://drive.upm.es/s/OqTrbdUlBqHMKBf/download) and let me know the result?
Regarding translations, if you can provide with shorter/better translations I can include them.

**Comment by temis01** [comment]
I can't install software on this rig, can you provide a portable patched zip ?
thanks.
And yes I can try to improve the french translation so it fits everywhere.

**Comment by eibol** [comment]
> I can't install software on this rig, can you provide a portable patched zip ? thanks. And yes I can try to improve the french translation so it fits everywhere.
[
Portable 3.1.0 patched](https://drive.upm.es/s/miyU6rqfAMaC0Ry/download)

**Comment by temis01** [comment]
Scaling is OK
Is the local text to check all in here  : "ffmpeg_batch-3.1.0\FFBatch\Properties\Strings.fr.resx"
or is there another text file to check ?

<img width="968" alt="overlapping tags patched 150%" src="https://github.com/user-attachments/assets/d4152ea7-4895-4cda-81f2-c8efc4529c23">

**Comment by eibol** [comment]
Great. Thanks.

The menus and french messages are all there in Strings.fr.resx, but the buttons captions, which are the more problematic, are distributed among the different form files, so I would have to do any change one by one.

**Comment by temis01** [comment]
Here is Strings.fr.resx
Some translation needed an obvious tweaking. But due to the lack of context I chose to leave them as is.
I will continue checking for the rest of the *.fr.resx file during my spare time.

**Comment by eibol** [comment]
I've included the new resx file.
It really need a review, translation was mostly automatic.
French speaking users will be grateful.

**Comment by temis01** [comment]
[Form1.fr.resx.txt](https://github.com/user-attachments/files/17719224/Form1.fr.resx.txt)
here is form1.fr.resx
Really not easy to figure out where the text is located cause practically none of them are in order ... how do you do that ? lol 

Tab 1 : Is bloated. You should Expand vertically it will add some clarity to the whole thing and you will be able to show the buttons' label in 1 line. Just saying this cause some translations were completely off and the good one is ... longer !!

tab 2 to 4 : there is plenty of room for you to re-organize everything and get room where buttons and labels are bloated.
.

**Comment by temis01** [comment]
LOL
<img width="970" alt="overlapping tags patched 150%-2" src="https://github.com/user-attachments/assets/dee02915-878d-4e05-9ea8-ee9166eb6982">

**Comment by eibol** [comment]
That's bad. I think french language was broken, I'll have to revert back to 3.0.9 and do some research.

**Comment by temis01** [comment]
here you go ... 
By the way I used notepad++ to open the resx files.
Notepad++ is quite reliable and never broke anything for me.

Let me know when you fix it ... till then good luck !

[Form8.fr.resx.txt](https://github.com/user-attachments/files/17729007/Form8.fr.resx.txt)
[Form31.fr.resx.txt](https://github.com/user-attachments/files/17729008/Form31.fr.resx.txt)
[Form3.fr.resx.txt](https://github.com/user-attachments/files/17729009/Form3.fr.resx.txt)
[Form13.fr.resx.txt](https://github.com/user-attachments/files/17729010/Form13.fr.resx.txt)
[Form18.fr.resx.txt](https://github.com/user-attachments/files/17729011/Form18.fr.resx.txt)
[Form21.fr.resx.txt](https://github.com/user-attachments/files/17729012/Form21.fr.resx.txt)
[Form22.fr.resx.txt](https://github.com/user-attachments/files/17729013/Form22.fr.resx.txt)
[Form23.fr.resx.txt](https://github.com/user-attachments/files/17729014/Form23.fr.resx.txt)
[Form25.fr.resx.txt](https://github.com/user-attachments/files/17729015/Form25.fr.resx.txt)
[Form27.fr.resx.txt](https://github.com/user-attachments/files/17729016/Form27.fr.resx.txt)
[Form28.fr.resx.txt](https://github.com/user-attachments/files/17729017/Form28.fr.resx.txt)
[Form29.fr.resx.txt](https://github.com/user-attachments/files/17729018/Form29.fr.resx.txt)
[Form20.fr.resx.txt](https://github.com/user-attachments/files/17729019/Form20.fr.resx.txt)
[Form2.fr.resx.txt](https://github.com/user-attachments/files/17729020/Form2.fr.resx.txt)
[Form19.fr.resx.txt](https://github.com/user-attachments/files/17729021/Form19.fr.resx.txt)
[Form16.fr.resx.txt](https://github.com/user-attachments/files/17729022/Form16.fr.resx.txt)
[Form14.fr.resx.txt](https://github.com/user-attachments/files/17729023/Form14.fr.resx.txt)
[Form11_2.fr.resx.txt](https://github.com/user-attachments/files/17729024/Form11_2.fr.resx.txt)
[Form11.fr.resx.txt](https://github.com/user-attachments/files/17729025/Form11.fr.resx.txt)

**Comment by eibol** [comment]
Thanks. It is being tough to find a solution for this.
I hope this [new patched version](https://drive.upm.es/s/3OWJjrbGHh3bIwD/download) does it. It does not include updated translations yet.
Just replace your current file.

**Comment by temis01** [comment]
it's night and day ! good job man !
still 2 things but its ok cf pics.
<img width="968" alt="20241113 - 150% - tab3" src="https://github.com/user-attachments/assets/c7b22935-c007-44cf-ab56-527cf1f8bd66">
<img width="968" alt="20241113 - 150% - tab4" src="https://github.com/user-attachments/assets/f131f11b-7518-41ea-b4a4-61182d0e0bfc">

**Comment by eibol** [comment]
[New version](https://drive.upm.es/s/pP0ievAyEfTv801/download) with some more corrections and rest of translations included.
It is really french a very descriptive/verbose :)

**Comment by temis01** [comment]
Nice !
<img width="1006" alt="NICE !" src="https://github.com/user-attachments/assets/10cb4b4e-4214-4307-a3f6-73b13a27b728">
