### ISSUE TITLE
3.1.0版在使用“批量字幕”压制带字幕的文件时，【总进度】【剩余时间】没有任何进度状态指示

### ISSUE THREAD

**Issue by Soizzer** [eibol/ffmpeg_batch#127]
3.1.0版在使用“批量字幕”压制带字幕的文件时，【状态】显示 ”处理中“，但是【总进度】【剩余时间】没有任何进度状态指示，只有【消耗时间】有显示内容。

之前的3.0.9版时，【总进度】【剩余时间】都有时间进度显示。

另外建议，使用“批量字幕”压制时可以显示的进度参数，做到同“批处理”压制时显示的一样，包括【平均比特率】【速度】【预估大小】等这些。

![屏幕截图 2024-11-15 033300](https://github.com/user-attachments/assets/f2a19ccd-036b-49bc-af4b-bd735164bec1)

**Comment by eibol** [comment]
Progress can take some time to be displayed. I've tested it myself and it seems to work fine.
You can [try this version 3.1.1](https://drive.upm.es/s/xz6DFAFdBxvu3Ig/download) preview with slight changes in progress info to check if it works better.

**Comment by Soizzer** [comment]
> 进度可能需要一些时间才能显示。我已经亲自测试过了，似乎运行良好。 您可以尝试[此版本 3.1.1](https://drive.upm.es/s/xz6DFAFdBxvu3Ig/download)预览版，对进度信息进行一些小改动，以检查它是否运行得更好。


![386347597-f2a19ccd-036b-49bc-af4b-bd735164bec1](https://github.com/user-attachments/assets/fd4688cd-de8e-4529-94c2-ca28709f09b9)

我说的是“**批量字幕**”（红圈部分），压制字幕时，时间已经过了7分钟了，可是进度指示条还是没有显示。

I'm talking about “Bulk Subtitles” (the part circled in red), where 7 minutes have passed while compressing the subtitles and the progress bar still doesn't show up.

**Comment by eibol** [comment]
Thanks, apologize for the problem. I may have found a possible cause for it.
Please try [this new patched version](https://drive.upm.es/s/xz6DFAFdBxvu3Ig/download).
