### ISSUE TITLE
Question about joining multipart video files...

### ISSUE THREAD

**Issue by MrMxyzptlk** [eibol/ffmpeg_batch#129]
Thank you for your app; I'm trying to figure out whether this will be useful for my needs.

I have a folder which various downloaders put sub-directories with video files into them.
Some are multipart files, but not all folders and files.

I would like to automatically join files in sub-folders to each other if they are multipart.

For instance: 

Root folder: 'Downloads'
     sub-folder: 'Video 1'
     sub-folder: 'Video 2'

'Video 1' contains video.mkv

'Video 2' contains euro trip-1.mkv, euro trip-2.mkv, euro trip-3.mkv

Is there a way to automatically join videos when they are downloaded into a folder such as 'Video 2', without any manual interaction?

Thank you for your time,
and if I'm not making any sense, I'm happy to answer additinal questions.

**Comment by eibol** [comment]
Hi, I'm afraid such feature like automatic concatenation is not implemented in the application.

**Comment by MrMxyzptlk** [comment]
I understand; thank you for your reply.
