### ISSUE TITLE
Enhnacement - Multilanguage installer

### ISSUE THREAD

**Issue by bovirus** [eibol/ffmpeg_batch#13]
@eibol 

Thankis for your program.

To enlarge the number of suers that can use your tool, could please consider to enable multilanguage GUI for your tool?

I can help you also with Inno Setup Multilanguage script to enable multilanguage installer.

Thanks.

**Comment by eibol** [comment]
Hi, that's an idea I've been considering for long, however, since the application was not intended to be translated from the beginning, now it would be a huge task to rewrite the whole application.

Translating the GUI would be feasible, the problem is translating hundreds, or thousands of string messages along the code.
I will give a thought anyway.

Thanks

**Comment by bovirus** [comment]
@eibol 

I thnink that could consider to translate first of all the GUI menu/options.

The translation of GUI is the necessary step to increase a lot the number of user that can use it.

**Comment by eibol** [comment]
I guess the whole process can be achieved bit by bit. I'll start with inno setup installer translation to spanish/italian. 
If you can help, I will pass you the installer strings that require translation.

**Comment by bovirus** [comment]
@eibol 

Please pass me the installer .iss Inno Setup script with Custom string and I will translate it on the fily.

Please provide me also the info about Inno Setup version are you using and if it's standard or Unicode.

**Comment by eibol** [comment]
Hi, you can [download the files here](https://drive.upm.es/index.php/s/YGnNJJUdMwRyRR4/download), I include english and some rough italian translation. The strings are also in the txt files.

**Comment by bovirus** [comment]
@eibold

I made some changes

**- Custom messages**

I ordererd the custom messages based on language code and not same string in all languages.
For me It's more clear for translator.

I suggest to avoid use of "your" (your computer/your settings, etc) and use without "your (computer, settings, etc) because your aren ot sure that are yours.

I added custom string about "Run FFmpeg Batch AV Converter"

**- App version**

I adeded the variable for app version to set it in only one place

#define ApplicationVersion=2.4.0

OutputBaseFilename=FFbatch_setup_{#ApplicationVersion}_x64
AppVersion={#ApplicationVersion}

**-Setup directive**

I adedd 

ShowLanguageDialog=yes
UsePreviousLanguage=yes

to show dialog about language selection and keep rpevious language selected

Please compile and send me the link for exe file.

**- Untranslated strings**
 
These parts about MsgBox are comments or are untranslated?

 //MsgBox('FFmpeg Batch A/V Converter version ' + DisplayVer + ' is already installed. ' #13#13 'It will be upgraded with new version' + ThisVersion, mbConfirmation, MB_OK)

MsgBox('FFmpeg Batch AV Converter version ' + DisplayVer + ' ' + Msg1 + #13#13 + Msg2, mbConfirmation, MB_OK)

//MsgBox('FFmpeg Batch A/V Converter version ' + DisplayVer + ' is already installed. ' #13#13 'It will be upgraded with new version' + ThisVersion, mbConfirmation, MB_OK)

 //  MsgBox('Error !!! ' #13#13 '' + SysErrorMessage(ResultCode) + '.', mbError, MB_OK);          

        if MsgBox('FFmpeg Batch A/V Converter requires Microsoft .NET Framework 4.6.1 or higher.'#13#13
            'Setup will continue after framework installation. Internet access is required.'#13#13
            'Press YES to launch .net installer.' #13
            'Press NO to skip .net installation.', mbConfirmation, MB_YESNO) = IDYES then

If you need and you can add relative strings in Custom messages.

New version of the script.

[FFBatch_installer_italian.zip](https://github.com/eibol/ffmpeg_batch/files/6534344/FFBatch_installer_italian.zip)

**Comment by eibol** [comment]
Hey, that's was great, I've kept all your modifications. The file was not compiling, just the syntax of the new ApplicationVersion #define

I have added some missing translated messages, 
[New setup version 2.4.0](https://drive.upm.es/index.php/s/LrdUhFBnInJupGn/download)

**Comment by eibol** [comment]
Thanks again! It's greate to have an expert in software tweaking code. It works like a charm.
I have [uploaded here](https://drive.upm.es/index.php/s/39L6WuNASCyuWLi/download) for review.
Cheers

**Comment by bovirus** [comment]
@eibol 

It seems that there is a problem regarding 

SetupWindowTitle=Install [name/ver] 64 bit
UninstallAppFullTitle=Uninstall [name/ver] 64 bit

The variable [name/ver] is not applied as value.

![image](https://user-images.githubusercontent.com/1262554/119554253-c144ee00-bd9c-11eb-921b-dd3e09541a7d.png)

I'm so sorry but without original source structure is not soe asy to make the necessary etst.

I hope that now with

SetupWindowTitle=Install %1 %2 64 bit
UninstallAppFullTitle=Uninstall %1 %2 64 bit

will be ok.

[FFbatch_AV_Converter_2.4.0_multi_lang.zip](https://github.com/eibol/ffmpeg_batch/files/6541728/FFbatch_AV_Converter_2.4.0_multi_lang.zip)

**Comment by eibol** [comment]
Hi, I think we are mixing script versions, in this latest one I can't find 
`#define ApplicationVersion '2.4.0'`

%1 works fine.
%2 does not display version yet. 

Maybe for that reason? I include [the scripts and all the required files](https://drive.upm.es/index.php/s/0Gt54ziO5Ci5M3w/download), so you can test it as you please.
Thanks

**Comment by bovirus** [comment]
@eilbol

I remove

#define ApplicationVersion '2.4.0'

because I red in previous post that you reort that didn't work ad was available only in 32bit script version.

I will check with all files.

Thanks.

**Comment by eibol** [comment]
Hi again, #define ApplicationVersion '2.4.0' actually works fine, it was just a tiny syntax error. 
You can include it or not, you decide, now that you can test the setup.
Thanks a lot

**Comment by bovirus** [comment]
@eibol 

Thanks to your files I made a fine tuning about .iss script

[FFBatch_Inno_Installer_Files.zip](https://github.com/eibol/ffmpeg_batch/files/6546326/FFBatch_Inno_Installer_Files.zip)

Pelase remind to edit script for final reelase to remove comemnt to include ffmpeg exe files and medianfo exe file.

Thanks.

**Comment by eibol** [comment]
Fantastic! I have tested it and everything looks good.
Now, it's time to start the application translation itself...i guess I shoudl start by collecting UI strings.

Any general recommendation for localization?
Thanks a lot

**Comment by bovirus** [comment]
@eibol 

Are you referring localziation of source code?

I'm no so big knowledge about resxz. localization.

Probably you should add some file like

AeroWizard1.xx.resx (ex AeroWizard1.it.resx) 

but I believe tht you have to setup something in other modules.

**Comment by bovirus** [comment]
@eibol

New version of the Inno Setup script

Add custom "WelcomLaabel1"
That now show Appname platform.

![image](https://user-images.githubusercontent.com/1262554/119717858-236a2580-be67-11eb-9ca3-123234f0305a.png)

Now in Program Add/Remove you have appname + platform.
Then you can install both 32bit and 64bit app version and in Program Add/Remove list you see both.

![image](https://user-images.githubusercontent.com/1262554/119718051-66c49400-be67-11eb-8a90-0acc6e60a73c.png)


Here teh enw scritp files

[FFBatch_Inno_Installer_Files.zip](https://github.com/eibol/ffmpeg_batch/files/6549136/FFBatch_Inno_Installer_Files.zip)

**Comment by eibol** [comment]
Cool, looks very nice. I'll use it like that  as soon as I manage the app translation. 

The gui translation is made easy by Visual Studio using .resx files. The messages inside the code are the thing that will take longer.
Can I send to you the english strings for translation, as soon as I have manage to collect them?

**Comment by bovirus** [comment]
@eibol 

Could you please in first step replace exe installer in Sourcefoprce with new multilanguage installer?

You can make a a silent update (remain v. 2.4.0) but now with multilanguage installer.

Could you pelase send me the list of strings?

**Comment by eibol** [comment]
Hi @bovirus, do you think it makes sense to put the multilanguage installer online when the application is still in english only?
I'm releasing v2.4.1 soon with some bugfixes.

Thanks for the localization info, I'm still collecting the many strings that need translation in a .resx file. As soon as I finish I will send the file to you.

**Comment by bovirus** [comment]
@eilbol

I beleieve that also if the GUI is monolanguage, the multilanguage installer that it's availabel it's a plus vs. current mono langhuage installer.

**Comment by eibol** [comment]
@bovirus ok, thanks.
