### ISSUE TITLE
Portable version creates folder '%LOCALAPPDATA%\Eibolsoft'

### ISSUE THREAD

**Issue by passat1** [eibol/ffmpeg_batch#132]
Hi,

I already reported problem with 'portable' version.
After your reply, I tested it again without included file 'ff_batch.ini' in folder 'settings'.
Pogram does create all files '*_portable.ini' in mentioned folder, but it also creates folder '%LOCALAPPDATA%\Eibolsoft' with subfolder 'FFBatch.exe_StrongName_xxxxxxxxxxxxx' and inside folder '3.1.2.0' with file 'user.config' where is also stored part of configuration.
So, program **does not** store **complete configuration** inside program folder ('settings').
If that folder ('%LOCALAPPDATA%\Eibolsoft') is deleted or complete 'portable' folder is moved to another system, it forgets configuration (theme, not detecting ffmpeg version, ...)
Because of that, it is **not really portable**.

**Comment by eibol** [comment]
Hi, apologize. I was not aware of such %LOCALAPPDATA%\Eibolsoft being created, It should all be constrained to application folder settings file and settings folder. I'll look into it. Thanks for the detailed report.

**Comment by eibol** [comment]
This [patched version](https://drive.upm.es/s/RuLyihSdGjcLVRx/download) seems to have solved the improper settings saving.
You could give a try.

**Comment by eibol** [comment]
Updated [fixed link](https://drive.upm.es/s/RuLyihSdGjcLVRx/download).

**Comment by passat1** [comment]
It is now working as 'real portable'.
But when '**ffmepeg.exe**' is added in program folder, on **first program run** it displays '**FFmpeg unknown version**'.
After **immediate exit**, without any other action, on another (2nd) program run, it recognizes 'ffmpeg.exe' and displays '**FFmpeg version 7.1.full**'.

If this **complete** 'portable' folder is moved to another location, after 2nd run (ffmpeg already recognized), it again does not recognize included ffmpeg on first run, but again on 2nd run in this new location.

Also, if on first run, in screen 'Application language' is selected 'User dark theme', then after confirmation (OK), program enters **without** showing '**FFmpeg Batch AV Converter Wizard**'.

**Comment by passat1** [comment]
In this latest version, on **first start** I get message '**File not found: ffmpeg.exe**', even if it is in program folder.
But now is displayed program logo, which was absent in previous versions. I forgot to mention it before.
After exit, on 2nd program run, it is correctly recognized as described in previous messages.

And again same situation when complete folder is moved to another location.
It finds and recognizes ffmpeg.exe on 2nd run.

About 'Application Wizard' I totally agree, because I'm also one with sensitive eyes and using all programs in dark mode.

**Comment by passat1** [comment]
YES 🥇 
This one is working as expected **when 'ffmpeg.exe' is included** in program folder.
Recognizing ffmpeg on first run, and also when moved to another location.

Now I also tested **downloading of 'ffmpeg.exe'** (started without it) and program is downloading it as '%TEMP%\FFBatch_test\ffmpeg-release-full.7z'.
But when it is finished, file 'ffmpeg.exe' is not in program folder. It is **probably** unpacked somewhere, but I can not find where, if it is at all.
File 'ffmpeg-release-full.7z' is deleted from folder 'FFBatch_test' but folder remains.
On next program run, I get 'Browse ffmpeg' window.

Sorry, but when I start 'digging' in some program, it becames almost 'never ending story'.

**Comment by eibol** [comment]
I have verified the download feature unpacks ffmpeg,exe in program folder and then deletes the .7zip file. 
7z.exe is required in application folder.

'FFBatch_test' folder is not deleted with application running because it stores other files like thumbnails, preset and console trials.
It is always removed on application exit and created again on startup.

**Comment by eibol** [comment]
Latest [patched version](https://drive.upm.es/s/RuLyihSdGjcLVRx/download) with one fix.

**Comment by passat1** [comment]
I tested this latest version, which deletes folder 'FFBatch_test' on exit, but I can not get file 'ffmpeg.exe' extracted in program folder.
'7z.exe' is in program folder, as it is already included in your 'FFBatch_312_Portable_fixed.zip'.
Before I started 'FFBatch.exe' from portable (PAF) 'Total Commander' which from 'launcher' gets different '%TEMP%' folder name.
Now I started it from 'Windows Explorer' and result is same.
Even tried from different source ('GitHub') and also file 'ffmpeg-release-full.7z' was downloaded (much faster), but was not unpacked in my program folder.
Just to mention, I have both (system and user) 'Environment Variables' 'TEMP' and 'TMP' **redirected** to one folder 'C:\TEMP'.
And program is located in 'E:\TEST\FFBatch_312_Portable_fixed'.
I also moved it to 'C:\TEST\FFBatch_312_Portable_fixed' with same result.
After download finishes, in program folder I get file '5lajbxvc.rne' or 'qcli4rtv.bve' but not 'ffmpeg.exe'.
When I try to **download second time in same program run**, 'Downloading ffmpeg.exe' appears with progress bar, but it is not downloading nor progress bar moves.
When I press 'Cancel', that file 'qcli4rtv.bve' (or similar) disappears from folder, but I can not restart download, unless I restart program.
Finally, it seems to me that '7z.exe' never starts (probably could not be found even if it's in program folder) because downloaded file 'disappears' in milliseconds after download is finished, and I was not able to see it (7z.exe) started at all in 'System Explorer' nor in 'Task Manager'.

If you can not solve this (for me), it is not much important (at moment) as I have downloaded 'ffmpeg.exe' and I'm including it in program folder manually. So, you can close this, as **basic problems** with **portable version** are solved.

Regards

**Comment by passat1** [comment]
I have found source of problem that will probably lead to solution.
I don't have installed 7-Zip program on my system.

I tested this portable on my VM (Virtual Machine) Windows 8.1 x64, with same result. No 'ffmpeg.exe'.
Then I installed '7z24.09-64.exe' on it, and after that, when selected 'Download ffmpeg', after downloading finished, got message 'Copy file ...', and file 'ffmpeg.exe' was extracted in program folder.
So, program 'FFBatch.exe' is **not using** '7z.exe' **from program folder**, but one that is **installed on system**.

Hope this will help you to solve this problem.

**Comment by passat1** [comment]
I just replaced '7z.exe' and added '7z.dll' from latest '7-Zip' 24.09 x86 package, because I don't have older, and everything works!
So, **only have to add '7z.dll'** and all problems are solved.
There is no need to change program behavior and force users to unpack 'zip' file, as complete procedure is already solved in your program.
It would be too much 'wasted' work.

Regards

**Comment by eibol** [comment]
So be it
