### ISSUE TITLE
Feature Request: load input files from file 

### ISSUE THREAD

**Issue by hairlesshobo** [eibol/ffmpeg_batch#16]
Hey! I love ffmpeg batch. I find it to be incredibly helpful and use it quite regularly. There is one bit of functionality that would be supe helpful for me and I was hoping you might have some extra time to add it.. Could you add a "add input files from file" button to the batch processing tab? Much like you do fit "add urls from file", it would be awesome to be able to load a list of input files from a file. Ideally, one input file per line. Would be very handy for batch processing the output of a script or similar.

Thanks in advance!

**Comment by eibol** [comment]
Hi, application localization is in progress to allow translations into other languages. For the moment new features are paused. Anyway, I'll take note of the request so text files with just filenames inside can be loaded into the application.

**Comment by eibol** [comment]
Hi, I have included the feature to load files from text file. You should be able to open a txt file with the application, or use open queue file feature to load all the files included in the text file. I hope it works as expected. Just replace your .exe with [this one](https://drive.upm.es/index.php/s/RUbqAQzlXJyQFlL/download).
