### ISSUE TITLE
Feature Request: Add Stereo3D

### ISSUE THREAD

**Issue by wes1993** [eibol/ffmpeg_batch#19]
Hello @eibol 
I love your software, in the last days i have managed to see video SBS via ffplay with this command:

ffplay  -vf stereo3d=sbs2l:arcd -i a.mkv

Could you add this filter so we can convert 3d SBS ecc video to anaglyph and see all this movie in any PC/TV/Mobile?
https://ffmpeg.org/ffmpeg-filters.html#stereo3d

Thanks a lot
Stefano

**Comment by eibol** [comment]
Hello @wes1993 

Where do you need to have this option added? It can be used in the parameters field as any other field. 
Do you mean in the wizard?

**Comment by wes1993** [comment]
Hello @eibol 
Thanks a lot for your reply and your Hint, I really love you software, it's the only complete video software that work very well!!!!!.
I have used the custom profile and it's a good functionality, my idea is, when you want and have time, to add some gui part like a new TAB, similiar to batch processing but only for 3D and various drop down menu or similiar with all settings that it's available for 3D.

Thanks a lot
Stefano

**Comment by wes1993** [comment]
SOme screen for my idea:
![image](https://user-images.githubusercontent.com/52070589/133569850-88d2f7ef-a3d4-4ab3-bbb4-4dfcb74e7165.png)
If you need some help with description/translation of IN and OUT option i'm happy to help you :-D
Unfortunately i don't know C so i can't help with the code.

Best Regards
Stefano

**Comment by eibol** [comment]
Thanks, it's clear. I understand this makes things easier for non-advanced users, but I'm afraid this request takes a long time. 
Users can create and save their own presets with their favourite Stereo·3D settings. Maybe a specific wizard with this features would be possible in the future.

**Comment by wes1993** [comment]
@eibol 
Thanks a lot for your reply.
I know this is not simple but i hope that one day we have this in the gui because, if you try to search on the web also there isn't anything that do this!! Every other software works bad... 

Best Regards
Stefano
