### ISSUE TITLE
Clarification about two icons

### ISSUE THREAD

**Issue by opusforlife2** [eibol/ffmpeg_batch#2]
I added a bunch of files for conversion. Normally, it parses all of them and it's all fine. This time, a few of those file names showed a red cross icon, and a few showed a green tick icon, both still in the filename column. There is no information on what these icons are for. Can you add a tooltip to them or something?

The files still converted successfully.

**Comment by eibol** [comment]
Icons should display next to status only, not filenames, looks like a bug. If you can send a bunch of files showing that behaviour I could try to reproduce it.

**Comment by opusforlife2** [comment]
How lucky for us the files are licensed under creative commons. XD
[test.zip](https://github.com/eibol/ffmpeg_batch/files/5011067/test.zip)

Two of these are fine, four are not. The green tick shows in the same place and has the same behaviour as the red cross.

**Comment by eibol** [comment]
I think I found the bug, just icon drawing mismanagement.
You could try the fix replacing your executable with [this one](https://drive.upm.es/index.php/s/h5SnXM8CIPJbw7n/download).

**Comment by opusforlife2** [comment]
Just tried it. No issue listing these files now. 👍

**Comment by eibol** [comment]
Great, thanks.
