### ISSUE TITLE
Auto-launch encoding?

### ISSUE THREAD

**Issue by fhtdtdj** [eibol/ffmpeg_batch#20]
Hi eibol
Thank you very much for your nice front-end.

I've set up custom presets and default output path; couldn't find where to put a default input path?
So I just created a shortcut with '"C:\...\FFBatch.exe" "C:\...\my default 'videos to reencode' folder" so it'll load all my videos. So now everything is ready as I need it.

Is there a way to further automate this and have my shortcut auto-launch "sequential encoding" after it loaded my folder's videos and default preset (or another defined preset?) without having to manually press the button?

Something like
'"C:\...\FFBatch.exe" -s (for sequential encoding, or -m for multi-file encoding) "C:\...\my default 'videos to reencode' folder" -p "preset_name" (uses default if not specified)

Hope that makes sense, I'm just learning about this stuff and realize I could do something similar with ffmpeg directly but would prefer the nice GUI with the progress bar, pause button, etc.

Also re: "open output folder on file completion" I use a replacement for Explorer (directory opus) so all my opened Explorer windows are opened in it; but for some reason this still opens the folder in Windows Explorer instead. (minor issue but just letting you know)

**Comment by eibol** [comment]
Hi, latest version 2.5.2 has an "autorun" feature at settings, below the default preset box.
You can also enable it at the main tab, the "A" button on the bottom left.

**Comment by fhtdtdj** [comment]
Awesome, thanks!
