### ISSUE TITLE
Why don't allow ":" in output path

### ISSUE THREAD

**Issue by ljhcage** [eibol/ffmpeg_batch#23]
Since i have videos from different disk, and i want set output path to one dir.
code at Form1.cs:24293

**Comment by eibol** [comment]
Hi, I don't get the point. ":" is not a valid character for a file/folder name.
You can use a single output path, though some times you have to check "Recreate source path".

**Comment by eibol** [comment]
In that field, only a relative path name is accepted, so ":" is not a valid folder name. 
You can write a folder name, like "mydir", or "mydir\dir2"
