### ISSUE TITLE
Translate to russian

### ISSUE THREAD

**Issue by xetrin** [eibol/ffmpeg_batch#25]
Hi! I want translate your program in russian language. What is needed for it?

**Comment by eibol** [comment]
Hi, thanks for the interest.
It is necessary to translate a lot of strings files. (Around 1500 strings).

You can use Visual Studio 2019 to open the resource string files.
There's also the GUI buttons and menus, those are in plain text.

**Comment by eibol** [comment]
[FF_Strings.zip](https://github.com/eibol/ffmpeg_batch/files/7506401/FF_Strings.zip)
[Resource_strings.zip](https://github.com/eibol/ffmpeg_batch/files/7506403/Resource_strings.zip)

**Comment by xetrin** [comment]
> Hi, thanks for the interest. It is necessary to translate a lot of strings files. (Around 1500 strings).
> 
> You can use Visual Studio 2019 to open the resource string files. There's also the GUI buttons and menus, those are in plain text.

Okey. Today I'll install VS 2019 and look it)

**Comment by eibol** [comment]
Great!
