### ISSUE TITLE
Form24 is not included in project

### ISSUE THREAD

**Issue by ljhcage** [eibol/ffmpeg_batch#26]
Form24 is not included in FFBatch_Converter.csproj, so I can't just clone the code and run it. And I wanna do some work for organizing the code. So could you please upload the latest version of the source code. Thanks again for your working of the program.

**Comment by eibol** [comment]
Apologize for the spagetti code, this was not intended to grow much.

**Comment by eibol** [comment]
Updating again, some changes for next release.

**Comment by eibol** [comment]
Right, I'll change it accordingly.

**Comment by ljhcage** [comment]
It looks like the "Form 17" - "Form 24" and "Form 4" wasn't uploaded.

**Comment by eibol** [comment]
Uploaded everything, I hope it is all this time.
I've fixed many bugs and added some features.

**Comment by eibol** [comment]
I've just seen your pull request, after uploading the new Form1.cs.

**Comment by eibol** [comment]
After the new release, I won't make any change until further notice to avoid these conflicts. (only minor bug fixes).

**Comment by ljhcage** [comment]
It's ok, I've already resolved the conflicts. 
And it's reporting errors missing "Program.cs, Properties\Strings.es.Designer.cs, Properties\Strings.es1.Designer.cs,Settings.cs" when I compile the latest code on repo, maybe there are still some mistakes.

**Comment by eibol** [comment]
Uploaded the missing files, fixed a couple of wrong file references.
I git clone everything and it seems to work fine, I think it is already fixed.

**Comment by eibol** [comment]
Uploaded a new form1.cs with some changes.

**Comment by ljhcage** [comment]
It's ok to clone and compile, so we can close this issue.
