### ISSUE TITLE
Subfolder checkbox pop-up indicates the wrong mode selected

### ISSUE THREAD

**Issue by kyleboddy** [eibol/ffmpeg_batch#29]
The intended function of this checkbox is reversed in the dialogues - when it is checked, a dialogue pops up when traversing the file tree and says "Subfolders not included" and vice versa.

The actual operation of the button works as intended. When the box is checked, subfolders are included. When the box is NOT checked, subfolders are NOT included. However, the pop-up dialogues indicate the opposite.

![image](https://user-images.githubusercontent.com/746351/145004515-2520096d-5ddf-4bea-b6bd-480a4cda3e44.png)

**Comment by eibol** [comment]
You're right, fixing right now. Thanks for the report.
