### ISSUE TITLE
Problem with Subs

### ISSUE THREAD

**Issue by moralia** [eibol/ffmpeg_batch#3]
Hi. First of all congratulations on this GREAT program.
Everything works perfect for me, but when I want to convert a subtitle from ASS to SRT the font size is very large, disproportionate.
The code that I put is c: s srt and it effectively converts it to .srt to reproduce better in plex but I have the problem of size. I have tried various commands to change the font size but it doesn't work.
Do you know any way to do it? I would like to convert 3 seasons of a series but I can't find a way to convert subtitles. THANK YOU

**Comment by eibol** [comment]
Hi, thanks for the input.
As far as I know, SRT is a text file, so font size depends on the playback application settings. 
However, it maybe possible to edit the srt file, but I never tested, like stated in this thread:

[](https://superuser.com/questions/1402467/is-it-possible-to-change-the-size-of-subtitle-text-from-an-srt-file-in-ffmpeg)
