### ISSUE TITLE
Preset directory?

### ISSUE THREAD

**Issue by kctdfh** [eibol/ffmpeg_batch#30]
It would be great to have a folder in the repository here where people can contribute presets for more advanced commands such as high quality .gif conversion and other custom FFmpeg commands. The pre-loaded presets cover a lot of ground but a "use at your own risk" repository of presets would be a great addition to this great tool!

**Comment by eibol** [comment]
Hi, I think it is a very good idea, expand presets has always been a pending question.
I have added a presets.txt file with some basic instructions, subject to improvement.
https://github.com/eibol/ffmpeg_batch/blob/master/Presets.txt

**Comment by eibol** [comment]
Moved to https://github.com/eibol/ffmpeg_batch/blob/master/presets.md
for better formatting.
