### ISSUE TITLE
Encoder Speed

### ISSUE THREAD

**Issue by WildEgoLee** [eibol/ffmpeg_batch#31]
I used hevc_cuvid and hevc_nvenc to compress my video under GTX1650 laptop and RTX2070Super，but why their speed was almost same?Wish you can give me some advice.Thank you!

**Comment by eibol** [comment]
I would ensure you have the latest video card drivers.
I don't know about differences in speed among video cards hardware encoding, maybe the case the powerful one can encode with higher quality though at the same rate.
