### ISSUE TITLE
For single file encodings, output summary displayed at the end.

### ISSUE THREAD

**Issue by mrjohnpoz** [eibol/ffmpeg_batch#32]
Is there anyway to turn this off?

I quite often do single files - and this is annoying.. I like the output folder opened.. But this popup serves no purpose for me.  And would just like to not display it.. TIA

**Comment by eibol** [comment]
I'll include a setting to not display that output popup on next release.

**Comment by mrjohnpoz** [comment]
Thank you so much!!  I love this software, pretty much use it everyday..

**Comment by mrjohnpoz** [comment]
just updated to 2.7.3 and now able to not get that popup on finish... Thank you so much!

**Comment by eibol** [comment]
You're welcome
