### ISSUE TITLE
Concatenation failed.

### ISSUE THREAD

**Issue by pastelaura** [eibol/ffmpeg_batch#36]
I am trying to join/merge together some files, but each time I try to do so, I get a "Concatenation failed" error, stating that "concat.txt" does not exist in the AppData local folder, but when I double check the AppData folder, the txt file is indeed there with the txt file having the file paths and names of the videos I am trying to join/merge.  
Am using the latest version of Batch AV converter - 2.7.4
Not sure if this is a user error by me or a bug with the software, but would appreciate some help.

**Comment by pastelaura** [comment]
Just the default ones
format: mp4 "-c copy"
"Use concatenation demuxer."
Stream copy is checked.

**Comment by eibol** [comment]
No issues found with that. I'd need a few filenames and your output path.

**Comment by pastelaura** [comment]
I have a total of 30 video files. Each one is named in order so like "1", "2", "3" etc without quotation marks. Nothing else in the names. Just the numbers. 
The output path is just set to the desktop.

**Comment by eibol** [comment]
Unable to reproduce any issue with that settings. 

Anyway you may paste your log file here, or some screenshoot.

**Comment by eibol** [comment]
Main screen button "View last log".

**Comment by eibol** [comment]
There maybe some problem with your filenames or paths. Without the full path and name I can't find any problem.
"Shadows" is a filename without extension? or part of a file path?

**Comment by pastelaura** [comment]
All files are in mp4 format. Shadow is a file path name. Should I make a single folder on the desktop, copy all of the videos into there and then try merging them that way?

**Comment by eibol** [comment]
Yes, I think that would be a good test.

**Comment by pastelaura** [comment]
Can confirm that that worked. I don't think it liked the spaces or any quotation marks in the file pathname. I am not sure if you could fix that in a later build, but if it is possible, that would be superb. 
And if you don't mind me asking while I am still here: what preset/parameters would you recommend to reduce the file size of a video in the program, yet maintain the quality?

**Comment by eibol** [comment]
It is a "bug", character "'", though allowed in filename, is used for concatenation settings too. I'll add a warning about it.
Regarding reduze file size, it's a matter of playing with size and quality factor until you find a good trade-off.
For example: -c:v libx264 -crf 25 -vf scale=1280:-1 -c:a aac 96K
If you increase crf value, quality and size decrease. The same with scale size (width).
For example: -c:v libx264 -crf 28 -vf scale=800:-1 -c:a aac 96K
