### ISSUE TITLE
version 2.7.5 - Installer and GUI issues

### ISSUE THREAD

**Issue by bovirus** [eibol/ffmpeg_batch#37]
@eibol 

Please check screenshot

![image](https://user-images.githubusercontent.com/1262554/158567766-34b282c9-7dc5-4669-a8dc-4b6231712f4a.png)

Problem on exe file properties related to InnO Setup variable setup

![image](https://user-images.githubusercontent.com/1262554/158567885-dbde27e0-07bd-42d7-b7c3-3ad52000707f.png)

Please change the etxt string

![image](https://user-images.githubusercontent.com/1262554/158567986-e3409699-7edf-4ccb-8e9a-6806738bb7f2.png)

Strings to change

![image](https://user-images.githubusercontent.com/1262554/158568046-8867e825-e16e-4ab4-8aeb-d763a28cdcc7.png)

Strins to change

![image](https://user-images.githubusercontent.com/1262554/158568108-0e809208-f1bd-4252-a8ac-cdbf6b570898.png)

String to change and some GUI (moving) changes

![image](https://user-images.githubusercontent.com/1262554/158568168-d1171f3a-d121-4638-abc6-78083e712f36.png)

String to translate

![image](https://user-images.githubusercontent.com/1262554/158568924-32d91178-ec97-4747-9840-aa76c1cad1f6.png)

String to change

**Comment by eibol** [comment]
Thanks for the input, I'll fix them for next release 2.7.6. 
"None" will have to stay like that for the moment, it comes from ffmpeg output itself. 
Also, "Matroska video", not a localized string yet.
