### ISSUE TITLE
Hovering mouse pointer makes field contents vanish

### ISSUE THREAD

**Issue by opusforlife2** [eibol/ffmpeg_batch#4]
Got the update to 2.2.5.

If you let the mouse pointer stay over a field, it makes the contents vanish temporarily until you move it to another list item. However, if you move to another field for the same list item, the contents stay vanished. This way, you can vanish all the fields except Status.

**Comment by eibol** [comment]
HI, thanks for the issue report. It will be solved for next release.
This test version should not display the bug: https://drive.upm.es/index.php/s/h5SnXM8CIPJbw7n/download

**Comment by opusforlife2** [comment]
Tested and confirmed!

**Comment by eibol** [comment]
Thanks
