### ISSUE TITLE
Two pass encoding

### ISSUE THREAD

**Issue by kctdfh** [eibol/ffmpeg_batch#40]
This isn't a priority per-se but it'd be nice to have two-pass encoding.
Currently I've tried doing it like this but the first pass fails because of the format:
![twopass](https://user-images.githubusercontent.com/28873487/168386072-e8069f5d-9b25-480e-9190-024ea53b9175.jpg)

Docs here: https://trac.ffmpeg.org/wiki/Encode/VP9

**Comment by eibol** [comment]
Hi @kctdfh Have you tried the Two pass enconding wizard?
![imagen](https://user-images.githubusercontent.com/907799/168443290-ec533b02-50fe-4414-8f8a-7edc8f2dbe1e.png)
