### ISSUE TITLE
Index out of range error

### ISSUE THREAD

**Issue by StarPicard** [eibol/ffmpeg_batch#41]
Hi, im getting the following error and the application is not starting encoding:

`************** Exception Text **************
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at FFBatch.Form1.BG_Seq_RunWorkerCompleted(Object sender, RunWorkerCompletedEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)
`
Hope you can help. Thx!

**Comment by eibol** [comment]
Hi, no idea about the cause. I would need to know the parameters / pre-input you are using, output format. 
A screenshot or screencast displaying the error moment would be useful.

**Comment by StarPicard** [comment]
Hi, this just happened when I clicked on "Sequential encoding"
<img width="1274" alt="Error" src="https://user-images.githubusercontent.com/8884658/169508135-787bed4a-2698-46f6-9cb4-768d8078dfbd.png">

**Comment by eibol** [comment]
Hi, I see you are using Nvida hardware encoding (hevc_nvenc). Does the problem occur with any other encoders? (libx264/libx65).
I'll post [here a beta](https://drive.upm.es/s/USUAq7uB4VI1ZGS/download) for testing purposes.

**Comment by StarPicard** [comment]
Hi, it happens with all presets i've tested so far.

**Comment by eibol** [comment]
I'd recommend to create a folder with a short name at your root folder and run the application from there.
Also, I may need a sample file that causes the issue (in case it happens with some files only, and not with others).

**Comment by StarPicard** [comment]
Ok, i'll test it and give Feedback.

**Comment by StarPicard** [comment]
Hi, it's a problem of the gpu-decode option. The problem with the other presets was, that it stays enabled after it has been choosen one time. When I don't choose anything in the gpu decode tab, gpu decoding is still working.

**Comment by eibol** [comment]
Good to know, it must be a refresh list issue. I would try refreshing and selecting the desired decoding option, to confirm the issue.
Thanks for the report.
