### ISSUE TITLE
Can not mux a short wav and avi files with FFmpeg Batch AV Converter

### ISSUE THREAD

**Issue by buruto** [eibol/ffmpeg_batch#44]
I have captured a short video with pcsx2 1.6.0 but pcsx2 1.6.0 created two files of the same time length:
1 avi file with the name that I chose without audio but only frames and 1 recording.wav file with the audio but without the frames.

I have read that FFmpeg Batch AV Converter can mux an avi file and a wav file into a video file that have both the frames of the input avi file and the audio from the wav file but when I try to mux both files I get the following error:

Multiplexing failed:
Possibly incompatible container for selected tracks.
You can check log file on main tab for more error information.

I tried to find the main tab to read the log file but I don't even find the main tab and the log file.

I don't understand this error and typing it into google didn't find anything

Please help me with this!!!

This is annoying me that pcsx2 1.6.0 video capture separates the frames and the audio into chosen named avi and recording.wav!

**Comment by eibol** [comment]
At Batch processing tab, you have the "View last log" button.
At Stream multiplex tab, I've tried muxing one avi video stream and one wave file, 
using format "avi" or "mkv" output format and it worked fine.

**Comment by buruto** [comment]
I will view last log first

**Comment by eibol** [comment]
You could send an screenshot of Stream multiplex tab, with the error.

**Comment by ValZapod** [comment]
Both AVI and WAV are containers (WAV is RIFF container, it can contain Dolby E sound, e.g., so lossy even).
