### ISSUE TITLE
error when parse option value "%fdur/2-1" as duration

### ISSUE THREAD

**Issue by tranvantruong801** [eibol/ffmpeg_batch#45]
Hello Eibol.
thank you for the great ffmpeg batch av converter, and i need your help,
i have 1 video 10 seconds long and i want to cut the video time with this request

-filter_complex "
[0:v]trim=start=1:end=%fdur/2-1,setpts=PTS-STARTPTS[v1];
[0:a]atrim=start=1:end=%fdur/2-1,asetpts=PTS-STARTPTS[a1];
[0:v]trim=start=%fdur/2+1:end=%fdur-1,setpts=PTS-STARTPTS[v2];
[0:a]atrim=start=%fdur/2+1:end=%fdur-1,asetpts=PTS-STARTPTS[a2];
[v1][a1][v2][a2]concat=v=1:a=1[v][a]" -map "[v]" -map "[a]"

your software can work with below syntax

-filter_complex "
[0:v]trim=start=1:end=4,setpts=PTS-STARTPTS[v1];
[0:a]atrim=start=1:end=4,asetpts=PTS-STARTPTS[a1];
[0:v]trim=start=6:end=9,setpts=PTS-STARTPTS[v2];
[0:a]atrim=start=6:end=9,asetpts=PTS-STARTPTS[a2];
[v1][a1][v2][a2]concat=v=1:a=1[v][a]" -map "[v]" -map "[a]"

but when i use %fdur instead of duration it gives an error

[trim @ 00000000006f6b00] Unable to parse option value "10/2-1" as duration
    Last message repeated 1 times
[trim @ 00000000006f6b00] Error setting option end to value 10/2-1.
[Parsed_trim_0 @ 0000000000754b40] Error applying options to the filter.
[AVFilterGraph @ 00000000006eee00] Error initializing filter 'trim' with args 'start=1:end=10/2-1'
Error initializing complex filters.
Invalid argument
Encoding test failed. CHECK OUTPUT ABOVE

i don't know how to parse option value "%fdur/2-1" as duration and make the software work properly

Can I apply multiple presets for this purpose?

i want to apply this parameter to batch cut my 10 min videos

Please help me with this!!!

**Comment by eibol** [comment]
Hello, there's no parsing error, only %fdur and %dur+1 are supported yet.
