### ISSUE TITLE
Suggestion: 2-Pass but functions like the existing presets

### ISSUE THREAD

**Issue by snowbie** [eibol/ffmpeg_batch#46]
Maybe this is already a goal for V3, but if not, it's something I'd really like to see.
I often use my own batch script with this large set of parameters, which is adapted from a Reddit post detailing "More efficient VP9 parameters"
```
ffmpeg -i "%vidpath%" -c:v libvpx-vp9 -pix_fmt yuv420p10le -pass 1 -quality good -threads 1 -profile:v 2 -lag-in-frames 25 -crf %crf% -b:v 0 -g 240 -cpu-used 1 -auto-alt-ref 1 -arnr-maxframes 7 -arnr-strength 4 -aq-mode 0 -tile-rows 0 -tile-columns 1 -enable-tpl 1 -row-mt 1 -f null NUL && ffmpeg -i "%vidpath%" -c:a libopus -b:a %abr%k -c:v libvpx-vp9 -pix_fmt yuv420p10le -pass 2 -quality good -threads 6 -profile:v 2 -lag-in-frames 25 -crf %crf% -b:v 0 -g 240 -cpu-used 1 -auto-alt-ref 1 -arnr-maxframes 7 -arnr-strength 4 -aq-mode 0 -tile-rows 0 -tile-columns 1 -enable-tpl 1 -row-mt 1 -f webm "%outpath%\%vidname%.webm"
```
You don't need to read the actual parameters aside from noticing CRF and the audio bitrate are variables I set for each file. When the wizard is used, you're pretty restricted as it goes straight to encoding. Being able to use 2-Pass as a normal preset would be much more convenient as I wouldn't need to spend more than a couple seconds slightly modifying values, kind of like a Handbrake queue.

**Comment by eibol** [comment]
Hi, such complex scenario is not expected to be available. 
Anyway, you can use the current two pass wizard and tweak parameters at the final screen to achieve your goal, something like this:

Pass 1: 
-c:v libvpx-vp9 -pix_fmt yuv420p10le -pass 1 -quality good -threads 1 -profile:v 2 -lag-in-frames 25 -crf 23 -b:v 0 -g 240 -cpu-used 1 -auto-alt-ref 1 -arnr-maxframes 7 -arnr-strength 4 -aq-mode 0 -tile-rows 0 -tile-columns 1 -enable-tpl 1 -row-mt 1 -f webm

Pass 2:
-c:a libopus -b:a 128K -c:v libvpx-vp9 -pix_fmt yuv420p10le -pass 2 -quality good -threads 6 -profile:v 2 -lag-in-frames 25 -crf 23 -b:v 0 -g 240 -cpu-used 1 -auto-alt-ref 1 -arnr-maxframes 7 -arnr-strength 4 -aq-mode 0 -tile-rows 0 -tile-columns 1 -enable-tpl 1 -row-mt 1

Format: webm

**Comment by snowbie** [comment]
Hmm okay. What about
