### ISSUE TITLE
Feature Request - Split by Chapters in Youtube

### ISSUE THREAD

**Issue by fossist** [eibol/ffmpeg_batch#48]
Chapters in youtube videos:

![image](https://user-images.githubusercontent.com/86028957/201857743-28f0d4bf-35e6-4983-a0a6-fe2c248662bf.png)

yt-dlp support splitting by chapters. This is useful for very long videos. No yt-dlp gui application supports this useful feature.

If you have time to implement this, also add serial number before chapter titles.

Thank you for making this amazing video encoder. I prefer it over Handbrake and Xmedia Recode. This is the best video encoder.

**Comment by eibol** [comment]
Hi, I'll take it into account for a future release.

**Comment by fossist** [comment]
![image](https://user-images.githubusercontent.com/86028957/202361596-6d589c3d-1f6f-4876-ba94-1c88c4afb467.png)

Perhaps this will help as mentioned on [yt-dlp](https://github.com/yt-dlp/yt-dlp):
Split video by chapters: Videos can be split into multiple files based on chapters using --split-chapters
