### ISSUE TITLE
Fixed window size?

### ISSUE THREAD

**Issue by PhoenixIV** [eibol/ffmpeg_batch#5]
Hi,

First, I was very hyped when I found this linked by you on StackOverflow.

I just installed the software and first thing I see: It does not fit my screen! The lower bit is hiding behind my Windows task bar and there seems to be no option to resize the window?

**Comment by eibol** [comment]
Hi, my bad. When I started this application, resposiveness was not required, it was just a small development for my limited programming abilities.

But time passed and it got some attention. I started adding features, too many packed on the main tab.
Now making it resizable and still looking good would be a buge task I cannot face for the moment.

Current minimum resolution for the application is 1280x768
You can use it at 1280x720, but taskbar would need to be hidden.

**Comment by PhoenixIV** [comment]
Get that. Please have my applause for your work. Still want to put my issues 🤷‍♂️😉
+1

**Comment by PhoenixIV** [comment]
I do not know how easy it is: Maybe you can give the file list section a dynamic height. It scrolls anyway.

**Comment by eibol** [comment]
I had the same idea. I'm afraid still many hours job. I will reduce a little bit the file list height on next release.
A resolution height lower than 768 is pretty rare now days.

**Comment by PhoenixIV** [comment]
True.
