### ISSUE TITLE
Bug - Concentation failed on Create Video from Still Images via Wizard

### ISSUE THREAD

**Issue by muge** [eibol/ffmpeg_batch#51]
In Wizard > Images to video wizard > Create a video from a list of images seems to cause an error on some values, not sure what is causing this, if it's some rounding error being read or it's something else entirely.
Doesn't work:
`Image Display Time 0.05, Frame rate 30, using a total of 16 frames`
Works
`Image Display Time 0.07, Frame rate 30, using a total of 16 frames`
No audio added, default options in format used.

Image filenames were: animation_##-##.png

<img src="https://user-images.githubusercontent.com/221161/202944604-5ee4888a-1b18-4b6b-8d7d-e5a83549a6ff.png" width="400">
<img src="https://user-images.githubusercontent.com/221161/202953329-8e423d88-4ae2-402d-8c13-ed1a034dce0a.png" width="400">

**Comment by eibol** [comment]
Hi, using Video from still images uses a fixed framerate, intended for non-experts. No error on this part.
Regarding the wizard issues, it can be caused by a variety of things. Those rounding oeprations are probably performed by ffmpeg itself, but it would be better to have a separated thread for it.

**Comment by muge** [comment]
Alright, I'll edit this and break out the rounding one to a separate thread. Cheers

**Comment by eibol** [comment]
Can you post a session log with this error displayed?

**Comment by muge** [comment]
```
FFmpeg log session: 11/22/2022 11:30:45 AM
-------------------------------
ffmpeg version 5.1.1-essentials_build-www.gyan.dev Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 12.1.0 (Rev2, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, concat, from 'C:\Users\USER\AppData\Local\Temp\concat.txt':
  Duration: 00:00:01.50, start: 0.000000, bitrate: 10 kb/s
  Stream #0:0: Video: png, rgba(pc), 816x624 [SAR 3780:3780 DAR 17:13], 25 fps, 25 tbr, 25 tbn
-to value smaller than -ss; aborting.

Exit code: 1
-----------------------
END OF LOG FILE

LOG SIZE: 1 KB
```
