### ISSUE TITLE
Feature Request - Option in Settings to Default the Output Path to Source Files Path

### ISSUE THREAD

**Issue by RoyceRemix** [eibol/ffmpeg_batch#54]
I just want the option to always default the outputs into the same path as the sources, so I don't always have to click into the Custom relative path dialogue, that's all - Thank you for this awesome tool, I always recommend it to all my other video editor friends!  <3

**Comment by eibol** [comment]
Hi, thanks for yout message. I think you can already save output path as source path, just enter the Custom relative path dialog, select "User Source path", click OK, and at main tab click on save path button.
![imagen](https://user-images.githubusercontent.com/907799/204762398-ceb6b5d5-4b0f-4665-9601-a8812360069e.png)

**Comment by RoyceRemix** [comment]
Omg ur so right, idk how it didn't click with my brain to hit the save button lol!  Legend, thank you!  :D
