### ISSUE TITLE
Can you extend the parameter character limit?

### ISSUE THREAD

**Issue by tranvantruong801** [eibol/ffmpeg_batch#55]
I need your help with your software again. I'm used to your software, it's great. But there is one small problem, the parameter character limit is too small so I can't write more (currently less than 1500 characters). Can you do that. I would appreciate it if an update to the parameter character limit issue was noticed.

**Comment by eibol** [comment]
OK. Thanks for the suggestion. I will increase it accept much lenghty parameters on next release.
