### ISSUE TITLE
Feature Request - Split by time stamps

### ISSUE THREAD

**Issue by ThomasFSynnes** [eibol/ffmpeg_batch#56]
Hi
Can you add the option to split a video at specific time points instead of fixed time interval / file size?
I know it is possible to do this using the trimming tool, but I have to do it over multiple steps and it takes a lot of time doing it so. 
Most other software I have used to do this can only render the files which takes time and effects the quality/file size. 
Maybe add this to the trimming tool so the user can use the preview thumbnails? 

Thank you for making such a useful program

**Comment by eibol** [comment]
Hi, thanks for the suggestion. It would take a lot of work, maybe for future releases. 
You could you try using:

mkvmerge -o output.mp4 --split chapters:all input.mp4

It splits without rendering.

**Comment by ThomasFSynnes** [comment]
This helps a lot, thanks

**Comment by eibol** [comment]
This [beta executable](https://drive.upm.es/s/b7X1hasyM6TqiY1/download) should work splitting by chapters of manual chapters sheet.
You can try it and let my know.
