### ISSUE TITLE
Bug- Dynamic parameters don't work on parameters field

### ISSUE THREAD

**Issue by iG8R** [eibol/ffmpeg_batch#58]
Hi.
Windows 10 (21H1, 19043.1415)
FFBatch v2.8.4

The title says for itself.

![FFBatch-Dynamic-parameters-2022-12-11_174132](https://user-images.githubusercontent.com/11407417/206913370-57d92603-c5b9-4bf3-9d95-31ac987fe923.jpg)

**Comment by eibol** [comment]
Hi, dynamic parameters only work inside graphical interface, not it command line. That is just plain ffmpeg executable.

**Comment by iG8R** [comment]
Thanks a lot, the "Try preset" button "say" that these parameters `-i %1 -c:v libvpx-vp9 -crf 50 -b:v 0 -c:a libvorbis -q:a 3 -y` are OK, but, as I understand, in essence, the `-i %1` parameter doesn't make sense in this context.

**Comment by eibol** [comment]
You can see the log file starting encoding with your parameters and then aborting.
The -i %1 parameter is automatically added for every list item, so it should not be added unless it is required for some additional source stream processing.

Variables are not implemented in CLI.

**Comment by iG8R** [comment]
Thank you a lot.
