### ISSUE TITLE
OPUS wizard: CBR/VBR and small bitrates

### ISSUE THREAD

**Issue by PhoenixIV** [eibol/ffmpeg_batch#6]
I just checked the wizard for OPUS and two things came up:

First, I can only choose CBR from a dropdown menu, but can then, **additionally**, tick VBR. This works fine, no major issue, but makes no sense.

More important (even though this can easily be solved by altering the generated parameters code): The lowest accepted bitrate is 64 kbps. But, especially with OPUS, bitrates like 32k (and lower!) are still common / producing great results.

The default suggested compression level is 5 if I am not wrong. The pre-set in the wizard is 10.

**Comment by eibol** [comment]
Hi, I will include these suggestions on next release.

**Comment by PhoenixIV** [comment]
> The default suggested compression level is 5 if I am not wrong. The pre-set in the wizard is 10.

I gave wrong information here. Default is 10.
Source: https://wiki.xiph.org/index.php?title=Opus_Recommended_Settings#Trading_Coding_Efficiency_with_CPU_Time

**Comment by eibol** [comment]
Right. I'll revert the default compression factor to 10 for next release, coming out by this the end of this month.

**Comment by PhoenixIV** [comment]
Yeah. Sorry. Thank you, @eibol ❤
