### ISSUE TITLE
Question - Is there an option to encode with a CUDA GPU?

### ISSUE THREAD

**Issue by iG8R** [eibol/ffmpeg_batch#60]
Hi.
The title says for itself.
Decoding with a CUDA GPU is good, but encoding is more crucial for the time reduction.

**Comment by eibol** [comment]
Hi, if you have a compatible ffmpeg.exe version, you can encode with CUDA, using the necessary parameters:
https://docs.nvidia.com/video-technologies/video-codec-sdk/ffmpeg-with-nvidia-gpu/

You can try full ffmpeg.exe version at gyan.dev
