### ISSUE TITLE
Feature Request - Samples

### ISSUE THREAD

**Issue by tom12011** [eibol/ffmpeg_batch#61]
This program is super useful for batch encoding, it's so useful that I just use it for anything FFMPEG encoding related. My computer isn't the fastest and changing settings means restarting the encoding process, Handbrake has a neat feature that lets you make 1-minute samples of your encoding to see if the settings are correct. Would the be possible to implement it here? Cheers

**Comment by eibol** [comment]
Hi, just add at the end of your parameters:
-t 60
and you should obtain your sample.
