### ISSUE TITLE
option to disable many files warning

### ISSUE THREAD

**Issue by TristisOris** [eibol/ffmpeg_batch#63]
this one.

![изображение](https://user-images.githubusercontent.com/1270117/216785787-500c8c99-91f0-4955-9f6a-989b79ae31cf.png)

**Comment by eibol** [comment]
Increased number of files to 100000 before any warning.
https://drive.upm.es/s/ikJ4YIXKzfaH1ar/download

**Comment by TristisOris** [comment]
great, thanks. can leave pc and don't wait for this warning.
