### ISSUE TITLE
Add Arabic translation in FFmpeg Batch

### ISSUE THREAD

**Issue by SWxEng** [eibol/ffmpeg_batch#64]
Hi

how Add Arabic translation in FFmpeg Batch ??

**Comment by eibol** [comment]
Hi, it requires to translate the application menus and dialog messages, it is a long task. 
If you have the time or know someone, I can send the english strings for translation.

**Comment by SWxEng** [comment]
@eibol 
yes me translate Arabic 
send to me english strings

**Comment by eibol** [comment]
Hi, these are the application strings in english:
You can use Visual Studio to edit them:
[Strings.zip](https://github.com/eibol/ffmpeg_batch/files/10811530/Strings.zip)

These ones are plain text.
[Menus_buttons.zip](https://github.com/eibol/ffmpeg_batch/files/10811534/Menus_buttons.zip)

**Comment by eibol** [comment]
He, I send it again.
[Forms_menus.zip](https://github.com/eibol/ffmpeg_batch/files/10816807/Forms_menus.zip)

**Comment by SWxEng** [comment]
[Forms_menus_Arabic_Egypt.zip](https://github.com/eibol/ffmpeg_batch/files/10817169/Forms_menus_Arabic_Egypt.zip)

**Comment by eibol** [comment]
Thanks. That was quick!
I'll include the translation for next release.

**Comment by eibol** [comment]
Arabic translation beta here:
https://drive.upm.es/s/X3u3ESFj63UhJDU/download

**Comment by SWxEng** [comment]
Ok
