### ISSUE TITLE
Avisynth Script Issues

### ISSUE THREAD

**Issue by ENunn** [eibol/ffmpeg_batch#65]
Hi, I have a few issues when running Avisynth scripts through FFBatch. I tried this on 2.8.5.

1. The duration of the script isn't shown correctly. It shows the duration of the first source file itself, but not the entire script. This means that if your script is longer than what's being reported, encoding will be stuck at 100% for a while until encoding is fully done.

**2.5.4**
![image](https://user-images.githubusercontent.com/19480682/221376190-7f13975b-6554-41e4-a06c-2fd42cfca325.png)
**2.8.5**
![image](https://user-images.githubusercontent.com/19480682/221376203-60cbb791-6e83-40fc-9e02-25eb6389632d.png)

2. The output file name is the same file name of the source, not the script. So if your source file is named title_t00, the output file name will be title_t00, even if your script is named avisynthstuff.avs. If you have one source in multiple scripts, output files will most likely be overwritten.

**2.5.4**
![image](https://user-images.githubusercontent.com/19480682/221376219-681b1a9f-c6f2-467a-b40f-57cee9709a3e.png)
**2.8.5**
![image](https://user-images.githubusercontent.com/19480682/221376223-467ac06b-fa22-4821-8c27-1403f0c943c6.png)

These issues do not happen on 2.5.4, and I've been staying on it because of these issues. Hopefully there will be a fix sometime down the line.

**Comment by eibol** [comment]
Hi, if you can send an script example, I'll do my best to fix these issues.

**Comment by ENunn** [comment]
Here's my script. you can replace "F:/dvd-blu ray rips/411VM Issue 64/Disc 1\title_txx" with anything and you can just have two video sources if you want.

```setmemorymax(63448)
v = lwlibavvideosource("F:/dvd-blu ray rips/411VM Issue 64/Disc 1\title_t00.mkv", fpsnum=30000, fpsden=1001)
a = lwlibavaudioSource("F:/dvd-blu ray rips/411VM Issue 64/Disc 1\title_t00.mkv")
AudioDub(v,a)
#delayaudio(-.178)
assumetff()
v1=last
v = lwlibavvideosource("F:/dvd-blu ray rips/411VM Issue 64/Disc 1\title_t01.mkv", fpsnum=30000, fpsden=1001)
a = lwlibavaudioSource("F:/dvd-blu ray rips/411VM Issue 64/Disc 1\title_t01.mkv")
AudioDub(v,a)
#delayaudio(-.178)
assumetff()
v2=last
v = lwlibavvideosource("F:/dvd-blu ray rips/411VM Issue 64/Disc 1\title_t02.mkv", fpsnum=30000, fpsden=1001)
a = lwlibavaudioSource("F:/dvd-blu ray rips/411VM Issue 64/Disc 1\title_t02.mkv")
AudioDub(v,a)
#delayaudio(-.178)
assumetff()
v3=last
v = lwlibavvideosource("F:/dvd-blu ray rips/411VM Issue 64/Disc 1\title_t03.mkv", fpsnum=30000, fpsden=1001)
a = lwlibavaudioSource("F:/dvd-blu ray rips/411VM Issue 64/Disc 1\title_t03.mkv")
AudioDub(v,a)
#delayaudio(-.178)
assumetff()
v4=last
v = lwlibavvideosource("F:/dvd-blu ray rips/411VM Issue 64/Disc 1\title_t04.mkv", fpsnum=30000, fpsden=1001)
a = lwlibavaudioSource("F:/dvd-blu ray rips/411VM Issue 64/Disc 1\title_t04.mkv")
AudioDub(v,a)
#delayaudio(-.178)
assumetff()
v5=last
v = lwlibavvideosource("F:/dvd-blu ray rips/411VM Issue 64/Disc 1\title_t05.mkv", fpsnum=30000, fpsden=1001)
a = lwlibavaudioSource("F:/dvd-blu ray rips/411VM Issue 64/Disc 1\title_t05.mkv")
AudioDub(v,a)
#delayaudio(-.178)
assumetff()
v6=last
v = lwlibavvideosource("F:/dvd-blu ray rips/411VM Issue 64/Disc 1\title_t06.mkv", fpsnum=30000, fpsden=1001)
a = lwlibavaudioSource("F:/dvd-blu ray rips/411VM Issue 64/Disc 1\title_t06.mkv")
AudioDub(v,a)
#delayaudio(-.178)
assumetff()
v7=last
v = lwlibavvideosource("F:/dvd-blu ray rips/411VM Issue 64/Disc 1\title_t07.mkv", fpsnum=30000, fpsden=1001)
a = lwlibavaudioSource("F:/dvd-blu ray rips/411VM Issue 64/Disc 1\title_t07.mkv")
AudioDub(v,a)
#delayaudio(-.178)
assumetff()
v8=last
v = lwlibavvideosource("F:/dvd-blu ray rips/411VM Issue 64/Disc 1\title_t08.mkv", fpsnum=30000, fpsden=1001)
a = lwlibavaudioSource("F:/dvd-blu ray rips/411VM Issue 64/Disc 1\title_t08.mkv")
AudioDub(v,a)
#delayaudio(-.178)
assumetff()
v9=last
v = lwlibavvideosource("F:/dvd-blu ray rips/411VM Issue 64/Disc 2\title_t00.mkv", fpsnum=30000, fpsden=1001)
a = lwlibavaudioSource("F:/dvd-blu ray rips/411VM Issue 64/Disc 2\title_t00.mkv")
AudioDub(v,a)
#delayaudio(-.178)
assumetff()
v10=last
v1++v2++v3++v4++v5++v6++v7++v8++v9++v10
normalize(0.8912)
#turnRight().Histogram().TurnLeft()
converttoyuv420(matrix="rec601", interlaced=true).convertbits(10)
prefetch(6)
```

**Comment by eibol** [comment]
Hi, I've addressed some issues in the beta using your script as example.
https://drive.upm.es/s/OqxmvRjf3ePBeTJ/download

**Comment by eibol** [comment]
Due to the complexity of avs scripts, it is almost impossible to get the total duration successfully in all cases.
You can send to me a N/A avs script example.

**Comment by ENunn** [comment]
Late but I think it seems to happen at random, so I'm not sure what example I can send. However, every Avs script I loaded into FFBatch shows the correct duration 100% of the time.
