### ISSUE TITLE
"Source audio" presets actually encode audio

### ISSUE THREAD

**Issue by JustinWebDev** [eibol/ffmpeg_batch#68]
Many of the "Source audio" presets actually encode the audio.  E.g.,
    "Video: Rotate 90 degress Clockwise to H264 + Source audio"
    -c:v libx264 -crf 21 -vf "transpose=1" -c:a aac -b:a 128K

(BTW, that particular preset has a typo: degress -> degrees)

**Comment by eibol** [comment]
Thanks, I'll change it for next release.
