### ISSUE TITLE
Filter by number of channels

### ISSUE THREAD

**Issue by roughnecks** [eibol/ffmpeg_batch#69]
Hello,

is this currently possible? I'm not finding a way to filter e.g. mono tracks.

Thanks

**Comment by eibol** [comment]
Hi, it is not possible directly, but you use the find string to filter it:

![imagen](https://user-images.githubusercontent.com/907799/233463913-b31eb29c-4a3f-4d24-b468-45d82d42cc4b.png)

**Comment by roughnecks** [comment]
Solved with MediaInfo, didn't try ffmpeg!

Thanks 👍
