### ISSUE TITLE
Overwrite with failed files

### ISSUE THREAD

**Issue by micceo** [eibol/ffmpeg_batch#71]
Hi! Awesome converter btw!

Toying around and felt confident that I could overwrite files. But.. the encode was unsuccessful and the files were overwritten. Is this by design? (my fault I should have checked that the encode was OK maybe.)

Below worked OK for mkv and mp4, but not for mov obviously.

Parameters:
`-map 0 -map_metadata 0 -vcodec hevc_qsv -preset slow -global_quality 22 -look_ahead 1 -c:a aac`
Format: mov
Overwrite: true
GPU: auto

Here is the log.

```
Multi-file log session: 2023-06-30 12:13:05
-----------------------------------------------------
Logging for: "20110610-103156-MVI_0098_Canon_IXUS_310_HS.MOV"

[out#0/mov @ 000001d95e1f0400] Codec AVOption look_ahead (Use VBR algorithm with look ahead) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.
frame=    0 fps=0.0 q=0.0 size=       0kB time=00:00:00.42 bitrate=   0.7kbits/s speed=14.1x    
frame=    1 fps=0.0 q=-0.0 Lsize=     235kB time=00:00:00.49 bitrate=3924.8kbits/s speed=1.03x    

Output \\h\bild\foto\2011\2011-06\2011-06-10\20110610-103156-MVI_0098_Canon_IXUS_310_HS.mov Success (OK)


--------End of "20110610-103156-MVI_0098_Canon_IXUS_310_HS.MOV" log--------


Logging for: "20110610-094039-MVI_0089_Canon_IXUS_310_HS.MOV"

[out#0/mov @ 00000222291f0900] Codec AVOption look_ahead (Use VBR algorithm with look ahead) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.
frame=    0 fps=0.0 q=0.0 size=       0kB time=00:00:00.42 bitrate=   0.7kbits/s speed=15.6x    
frame=    1 fps=0.0 q=-0.0 Lsize=     298kB time=00:00:00.49 bitrate=4971.3kbits/s speed=0.992x    

Output \\h\bild\foto\2011\2011-06\2011-06-10\20110610-094039-MVI_0089_Canon_IXUS_310_HS.mov Success (OK)


--------End of "20110610-094039-MVI_0089_Canon_IXUS_310_HS.MOV" log--------


Logging for: "20170609-091130-MVI_4447_video.MOV"

[out#0/mov @ 0000023b95bb3040] Codec AVOption look_ahead (Use VBR algorithm with look ahead) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.
frame=    0 fps=0.0 q=0.0 size=       0kB time=00:00:00.89 bitrate=   0.3kbits/s speed=33.8x    
frame=    1 fps=0.0 q=-0.0 Lsize=     336kB time=00:00:00.93 bitrate=2929.7kbits/s speed=1.84x    

Output \\h\bild\foto\2017\2017-06\2017-06-09\20170609-091130-MVI_4447_video.mov Success (OK)


--------End of "20170609-091130-MVI_4447_video.MOV" log--------


Logging for: "20101230-031649-MVI_9125_video.MOV"

[out#0/mov @ 0000022cf81d7c80] Codec AVOption look_ahead (Use VBR algorithm with look ahead) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.
frame=    0 fps=0.0 q=0.0 size=       0kB time=00:00:00.89 bitrate=   0.3kbits/s speed=  36x    
frame=    1 fps=0.0 q=-0.0 Lsize=     194kB time=00:00:00.93 bitrate=1689.2kbits/s speed= 1.9x    

Output \\h\bild\foto\2010\2010-12\2010-12-30\20101230-031649-MVI_9125_video.mov Success (OK)


--------End of "20101230-031649-MVI_9125_video.MOV" log--------


Logging for: "20161221-094314-MVI_3900_video.MOV"

[out#0/mov @ 00000159305b04c0] Codec AVOption look_ahead (Use VBR algorithm with look ahead) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.
frame=    0 fps=0.0 q=0.0 size=       0kB time=00:00:00.89 bitrate=   0.3kbits/s speed=39.4x    
frame=    1 fps=0.0 q=-0.0 Lsize=     307kB time=00:00:00.93 bitrate=2678.6kbits/s speed=2.22x    

Output \\h\bild\foto\2016\2016-12\2016-12-21\20161221-094314-MVI_3900_video.mov Success (OK)


--------End of "20161221-094314-MVI_3900_video.MOV" log--------


Average performance: 140,2x  |  3443 fps

5 file(s) queued
5 file(s) successfull
0 error(s).
0 warning(s).

-------------------------------------------------------
END OF LOG FILE
------------------------------------------------------

LOG SIZE: 3 KB
```

**Comment by eibol** [comment]
Hi, the application uses the ffmpeg exit code to decide if file should be overwritten or not.
I see some initial warning for every file, but output says OK, that means that ffmpeg.exe considered exit code was 0 because
there was no fatal error.

**Comment by micceo** [comment]
The resulting files where just a couple of 100kb and was not playable. So even if the error was noon fatal the resulting file was not usable.

Now I've got even more strange behavior. It did overwrite a file even though I had disabled overwrite. Se second log here. I missed to uncheck overwrite.

To sum it up

- Overwrite Enabled, dest and src catalog the same. Src overwritten with broken file.
- Overwrite Disabled, dest and src catalog the same. Src overwritten with broken file.
- Overwrite Disabled, dest and src different. Works and produce a working file.

Did some more testing. Enabled Overwrite and it produces a file which can't be played:
```
FFmpeg log sesion: 2023-06-30 14:39:50
-------------------------------
---------------------Start of 20110610-103156-MVI_0098_Canon_IXUS_310_HS.MOV log-------------------------------

[out#0/mov @ 0000026649630300] Codec AVOption look_ahead (Use VBR algorithm with look ahead) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.
frame=    0 fps=0.0 q=0.0 size=       0kB time=00:00:00.42 bitrate=   0.7kbits/s speed=17.9x    
frame=    1 fps=0.0 q=-0.0 Lsize=     235kB time=00:00:00.49 bitrate=3924.8kbits/s speed=1.27x    

Output C:\Users\micce\Videos\konverterat\owerwrite-test\20110610-103156-MVI_0098_Canon_IXUS_310_HS.mov Success (OK)

---------------------End of 20110610-103156-MVI_0098_Canon_IXUS_310_HS.MOV log-------------------------------


Average performance: 189x  |  4544 fps

1 file(s) queued
1 file(s) successfull
0 error(s).
0 warning(s).

-------------------------------------------------------
END OF LOG FILE
------------------------------------------------------

Total time: 00h:00m:01s
LOG SIZE: 1 KB
```

Did some more testing. DISABLED Overwrite and it produces a file which can't be played AND did owerwrite the source file as I missed to change destination folder.

```
FFmpeg log sesion: 2023-06-30 14:51:02
-------------------------------
---------------------Start of 20110610-103156-MVI_0098_Canon_IXUS_310_HS - Copy.MOV log-------------------------------

[out#0/mov @ 00000235ad1a5740] Codec AVOption look_ahead (Use VBR algorithm with look ahead) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.
frame=    0 fps=0.0 q=0.0 size=       0kB time=00:00:00.42 bitrate=   0.7kbits/s speed=16.9x    
frame=    1 fps=0.0 q=-0.0 Lsize=     235kB time=00:00:00.49 bitrate=3924.8kbits/s speed= 1.3x    

Output C:\Users\micce\Videos\konverterat\owerwrite-test\20110610-103156-MVI_0098_Canon_IXUS_310_HS - Copy.mov Success (OK)

---------------------End of 20110610-103156-MVI_0098_Canon_IXUS_310_HS - Copy.MOV log-------------------------------


Average performance: 189x  |  4544 fps

1 file(s) queued
1 file(s) successfull
0 error(s).
0 warning(s).

-------------------------------------------------------
END OF LOG FILE
------------------------------------------------------

Total time: 00h:00m:01s
LOG SIZE: 1 KB
```

And different src and dest, which produces a working file (mov)
```
FFmpeg log sesion: 2023-06-30 15:08:46
-------------------------------
---------------------Start of 20110610-103156-MVI_0098_Canon_IXUS_310_HS.MOV log-------------------------------

[out#0/mov @ 0000013f93cd0300] Codec AVOption look_ahead (Use VBR algorithm with look ahead) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.
frame=    0 fps=0.0 q=0.0 size=       0kB time=00:00:00.42 bitrate=   0.7kbits/s speed=11.1x    
frame=   19 fps=0.0 q=-0.0 size=     256kB time=00:00:01.42 bitrate=1467.4kbits/s speed=2.65x    
frame=   66 fps= 61 q=-0.0 size=    1024kB time=00:00:03.43 bitrate=2442.4kbits/s speed=3.18x    
frame=  110 fps= 66 q=-0.0 size=    1536kB time=00:00:05.44 bitrate=2313.1kbits/s speed=3.24x    
frame=  146 fps= 62 q=-0.0 size=    1792kB time=00:00:06.93 bitrate=2117.4kbits/s speed=2.92x    
frame=  177 fps= 62 q=-0.0 size=    2048kB time=00:00:07.95 bitrate=2108.4kbits/s speed=2.77x    
...
frame= 4485 fps= 50 q=-0.0 size=   56064kB time=00:03:07.81 bitrate=2445.3kbits/s speed=2.09x    
frame= 4544 fps= 50 q=-0.0 Lsize=   57621kB time=00:03:09.50 bitrate=2490.9kbits/s speed= 2.1x    

Output C:\Users\micce\Videos\konverterat\owerwrite-test\20110610-103156-MVI_0098_Canon_IXUS_310_HS.mov Success (OK)

---------------------End of 20110610-103156-MVI_0098_Canon_IXUS_310_HS.MOV log-------------------------------


Average performance: 2,1x  |  50 fps

1 file(s) queued
1 file(s) successfull
0 error(s).
0 warning(s).

-------------------------------------------------------
END OF LOG FILE
------------------------------------------------------

Total time: 00h:01m:31s
LOG SIZE: 12 KB
```

Hopes this gives some clue or an answers if I do anything wrong here.

**Comment by micceo** [comment]
HI!

The first test when I encountered the problem I think I used the Multi-file encoding, this was also done on a network share (UNC-path). The above test were done with Sequential encoding.
Network shares. I've tested both. the last test was from a network share (UNC-path) to a local folder. The two first tests was done only on local folders, the path which is shown in the logs, C:\Users\micce\Videos\konverterat\owerwrite-test

![image](https://github.com/eibol/ffmpeg_batch/assets/31602021/f6a48ed3-3118-4631-afcf-4624fe854e84)
![image](https://github.com/eibol/ffmpeg_batch/assets/31602021/7f7ff3df-f329-4f4d-80c2-9e10ba0bf6a8)
![image](https://github.com/eibol/ffmpeg_batch/assets/31602021/635bc5f3-caf9-45b9-9754-5a7bfd914612)

**Comment by eibol** [comment]
Hi, I can't reproduce the issue. Could I check an screenshot with your application settings?
I've generated a [modified version](https://drive.upm.es/s/9MXsd6OED7r01w5/download), for testing purposes.

**Comment by micceo** [comment]
Hi!
Forgot to mention that I've replace ffmeg with https://www.gyan.dev/ffmpeg/builds/ release build 6.0 (2023-03-04). So I reverted back to the ffmpeg that's in your distribution to test. I made new installation and setup the parameters/settings I used before. Same thing happens the source file is overwritten with a non working file. Using any other format than mov works as intended what I can figure.

Re did the above with the modified version 2.8.8 used with ffmpeg full 6.0. Same-same, the source file is overwritten.

Screen-dumps here (2.8.7) is from when the file gets unusable and overwritten. I get no warnings that the file is being overwritten.
![image](https://github.com/eibol/ffmpeg_batch/assets/31602021/694af274-7422-4adc-8fcf-773394b3c258)
![image](https://github.com/eibol/ffmpeg_batch/assets/31602021/4a0b6f75-24c6-44e4-a526-00a7de9716a8)

And the log from the above convert:
```
FFmpeg log sesion: 2023-07-01 06:32:04
-------------------------------
---------------------Start of 20110802-165328-MVI_0129_Canon_IXUS_310_HS.MOV log-------------------------------

[out#0/mov @ 000001d0de02b3c0] Codec AVOption look_ahead (Use VBR algorithm with look ahead) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.
frame=    0 fps=0.0 q=0.0 size=       0kB time=00:00:00.42 bitrate=   0.7kbits/s speed=23.4x    
frame=    1 fps=0.0 q=-0.0 Lsize=     523kB time=00:00:00.49 bitrate=8730.1kbits/s speed=1.42x    

Output C:\Users\micce\Videos\konverterat\owerwrite-test\20110802-165328-MVI_0129_Canon_IXUS_310_HS.mov Success (OK)

---------------------End of 20110802-165328-MVI_0129_Canon_IXUS_310_HS.MOV log-------------------------------


Average performance: 26x  |  642 fps

1 file(s) queued
1 file(s) successfull
0 error(s).
0 warning(s).

-------------------------------------------------------
END OF LOG FILE
------------------------------------------------------

Total time: 00h:00m:01s
LOG SIZE: 1 KB
```

**Comment by eibol** [comment]
Hi, I could finally reproduce the issue, thanks for the screenshots.
As you can see the source file extension is .MOV, but the output format is .mov

Looks like filename mathing is case sensitive. if you use either .MOV or .mov in both source file and format, the problem is no more.

**Comment by eibol** [comment]
This[ patched version](https://drive.upm.es/s/9MXsd6OED7r01w5/download) should warn of mathing input and output files with different case extensions are not supported to avoid unintended overwriting.

**Comment by micceo** [comment]
Ah, I hadn't spotted that difference. Good with a warning if one encounter this scenario. But, isn't possible or a good thing to do this case insensitive? Windows users aren't prepared for discrepancy with case sensitive stuff when it comes to files 🤪

**Comment by eibol** [comment]
You're are so right 😄 it is not easy to take every conflicting user scenario into account.
What would you do, automatic source file renaming?

**Comment by micceo** [comment]
Don't think anyone opposes that intervention to solve this potentially odd occurrence.
The case of the extension isn't something crucial and having them automatically changed into lowercase is fine with me.

Is it ffmpeg that acts up here with the MOV and mov extension? If not, is it possible to just treat all extension as lowercase regardless what the filename has?

**Comment by eibol** [comment]
It is not something related to ffmpeg, but .net API comparer, upper/lower case is ignored except for extension.
I'll force lower case for extension everywhere so this odd situation is not possible.
[Patched version here](https://drive.upm.es/s/9MXsd6OED7r01w5/download).

**Comment by micceo** [comment]
Think that the way to handle it.

Thank you for the swift and pleasant handling of the issue. Happy coding!

I got some other ideas for usability and other things. Should I post this here too? (in separate threads of course).
I'm using your tool to convert bunch of old videos taken with older camcorder, cameras and phones. They're huge compared to a good compressed hevc. So far awesome!

**Comment by eibol** [comment]
Hi, I'm now through a rough patch, so I'm only on only critical bugfixes and easy to implement features.
You can post any idea, always welcome.
