### ISSUE TITLE
Strings.ar-EG,resx/Strings2.ar-EG,resx files in /FFBatch and /FFBatch/Properties

### ISSUE THREAD

**Issue by bovirus** [eibol/ffmpeg_batch#72]
@eibol 

Hi.

In the folderù

https://github.com/eibol/ffmpeg_batch/tree/master/FFBatch

there are two files

- Strings.ar-EG,resx
- Strings2.ar-EG,resx

and the dsame file name is available in

https://github.com/eibol/ffmpeg_batch/tree/master/FFBatch/Properties

Is it right?

Thanks.

**Comment by eibol** [comment]
They are redundant, from some translation tests, I've removed them, only the ones in Properties remain.
Thanks
