### ISSUE TITLE
Batch subtitles 

### ISSUE THREAD

**Issue by GiBiT** [eibol/ffmpeg_batch#74]
Is it possible to add a way for the batch subtitles to automatically recognize `subtitlename.{languageCode}.srt` or even better use the _Subtitles Language_  dropdown that is already on that screen to search for subtitles containing the selected language with maybe a little refresh button next to it or something.?

**Comment by eibol** [comment]
Hi, I'll look into it for future releases.

**Comment by eibol** [comment]
You can now use filename.3letterlangcode.srt and language is set automatically when adding input or sub files.
You can try it here [Patched version here](https://drive.upm.es/s/b7X1hasyM6TqiY1/download).

**Comment by GiBiT** [comment]
I may or may not have patched right. I just opened the directory and copied the patch into the folder and override? 

If that’s all. It didn’t auto detect for me. My subtitle file is {file name}.en.srt. 

This also in fact drew an error. I put 3 files into the queue for batch subtitling and it ran through one fine but switching to the next it must of fataled because the program quit. Seems like with this patch, I can only do one at a time. 

I’d love to provide some logs on that issue but I’m not sure where those are located. 

OS: Windows.

**Comment by eibol** [comment]
Hi, language Codes are three letrero (eng).
Regarding other issue, I'll have to do more testing.
If previous versión works fine, it would be a good starting point.
