### ISSUE TITLE
Batch merge doesn't give the correct duration

### ISSUE THREAD

**Issue by throwaway1908** [eibol/ffmpeg_batch#75]
Hi, as the title states, the batch merge feature this program has doesn't work as expected. For example, I put together about 30 videos into one MP4 file. The total duration length of that file should be roughly 48 minutes once merged. Instead, the program merges it into a length of 1 hour and 34 minutes, messing up the playback in the process. If you are able to fix this bug, that will make me a happy camper.

**Comment by eibol** [comment]
Hi, merging (joining) videos can be tricky, results vary depending on the input files (are all the same qualities?),
the settings used (concatenation filter using stream copy with -c copy, other encoding parameters), or using video filter which re-encodes output.
If you could provide more info about input files, concatenation mode and parameters, I could help. Even some screenshot/screencast.

**Comment by throwaway1908** [comment]
> Hi, merging (joining) videos can be tricky, results vary depending on the input files (are all the same qualities?), the settings used (concatenation filter using stream copy with -c copy, other encoding parameters), or using video filter which re-encodes output. If you could provide more info about input files, concatenation mode and parameters, I could help. Even some screenshot/screencast.

Hey thanks for replying!
The videos that I joined together were all in the same quality (4k, 60fps) and format (.mp4). 
The setting I used to join the files together was simply the default "-map 0 -c:v copy -c:a aac -cutoff 20K -b:a 256K -ac 2" parameters. No filters or anything.

**Comment by eibol** [comment]
> > Hi, merging (joining) videos can be tricky, results vary depending on the input files (are all the same qualities?), the settings used (concatenation filter using stream copy with -c copy, other encoding parameters), or using video filter which re-encodes output. If you could provide more info about input files, concatenation mode and parameters, I could help. Even some screenshot/screencast.
> 
> Hey thanks for replying! The videos that I joined together were all in the same quality (4k, 60fps) and format (.mp4). The setting I used to join the files together was simply the default "-map 0 -c:v copy -c:a aac -cutoff 20K -b:a 256K -ac 2" parameters. No filters or anything.

What setting did you select here?
![imagen](https://github.com/eibol/ffmpeg_batch/assets/907799/48e79b4b-840b-4694-b352-e9383d1672ff)

**Comment by throwaway1908** [comment]
> > > Hi, merging (joining) videos can be tricky, results vary depending on the input files (are all the same qualities?), the settings used (concatenation filter using stream copy with -c copy, other encoding parameters), or using video filter which re-encodes output. If you could provide more info about input files, concatenation mode and parameters, I could help. Even some screenshot/screencast.
> > 
> > 
> > Hey thanks for replying! The videos that I joined together were all in the same quality (4k, 60fps) and format (.mp4). The setting I used to join the files together was simply the default "-map 0 -c:v copy -c:a aac -cutoff 20K -b:a 256K -ac 2" parameters. No filters or anything.
> 
> What setting did you select here? ![imagen](https://user-images.githubusercontent.com/907799/258636749-48e79b4b-840b-4694-b352-e9383d1672ff.png)

The settings that are currently selected in that screenshot is what I used.
