### ISSUE TITLE
Cleanup language files list (,resx files)

### ISSUE THREAD

**Issue by bovirus** [eibol/ffmpeg_batch#78]
@eibol 

Could be possible to make a check/cleanup and alignmet about language files.

- Form3
Why "Fortm3-bad.xxx" files?
Is it necessary?
Could you pelase delete it?

- Form15
Why Form15 - Copia (2).es.res
Is it necessary?
Could you pelase delete it?

- Form24
Why only ar-eg language? 
Why not other language?

- Form26
Why only ar-eg? 
Why not other language?
 
In "Properties" subfolder

- Strings.zh-Hans_OK
Why "Strings.zh-Hans_OK.*" files?
Is it necessary?
Could you please delete it?

**Comment by eibol** [comment]
Thanks for the repot, I've removed all the old files, I've noticed that in Form26 I'm missing the language resources,
I'll upload them as soon as possible.

**Comment by bovirus** [comment]
@eibol 

Please check again.

- Form3_Bad
Why "Fortm3-bad.xxx" files?
Is it necessary?
Could you pelase delete it?

- Form24
Form24 has not language.
And string in master lamguage are mix of differnt languages.

**Comment by eibol** [comment]
Done, _Bad was a backup due to some issues, I had not removed yet.
Form24, I have removed other languges resources, none were necessary since language is applied programatically.

**Comment by bovirus** [comment]
OK. Thanks.
