### ISSUE TITLE
network paths

### ISSUE THREAD

**Issue by tommyhome** [eibol/ffmpeg_batch#79]
Hi,
I'm loadning the files over my local network via windows networking  \\192.168.1.100, which works fine draging and dropping or browsing and loading, but it is impossible to load a saved file with such paths and when closing and opening the program all of them disappear.

if I mount the same location as a network drive the program opens again with the files still there and a saved file with such paths works fine to load.

I'm a new user, using version: 3.0.0.

**Comment by eibol** [comment]
Hi, there was a bug saving queue files iwht network shares files.
It should be fixed in this [patched executable](https://drive.upm.es/s/b7X1hasyM6TqiY1/download).

**Comment by eibol** [comment]
Fixed in latest release.
