### ISSUE TITLE
Output path ignoring ../

### ISSUE THREAD

**Issue by PhoenixIV** [eibol/ffmpeg_batch#8]
Just started my first conversion, using the default output path "..\FFBatch".

I expect this to go up one level (..\) and create a new folder there, like this:

```
FFBatch
- 1.opus
- 2.opus
My music
- 1.mp3
- 2.mp3
```

But it does:
```
My music
- FFBatch
- - 1.opus
- - 2.opus
- 1.mp3
- 2.mp3
```

Do I see something wrong?

**Comment by eibol** [comment]
I don't understand this question. With relative path "..\FFBatch" output file is saved on a subfolder FFBatch from source path.
Source: C:\My Music\file1.wav Destination: C:\My Music\FFBatch\file1.opus

And lilke this with every input file.
C:\My Music\folder2\file2.wav  => C:\My Music\folder2\FFBatch\file2.opus

You can also select an absolute output path, like C:\Destination, and enabling "Recreate source path":
C:\My Music\file1.wav  -------------> C:\Destination\My Music\file1.opus
C:\My Music\folder2\file2.wav  -----> C:\Destination\My Music\folder2\file2.opus

Is that ok?

**Comment by PhoenixIV** [comment]
Ah, nice hint with the "Recreate source path"!

What I mean: The "../" notation means "Go up one folder". So if the path is "..\FFBatch" my idea has been that the new "FFBatch" folder is gonna be above the current (Folder "Music" and "FFBatch" next to each other in the same parent ../ directory).
For "create a subdirectory" I would expect the path to be just "FFBatch", or maybe "<Source folder>\FFBatch". I do not know how to explain better.
Maybe as question: Why is there "..\" at the beginning of the output path?

**Comment by eibol** [comment]
The ..\ is just a way of representing a relative path, relative to a previous, input source, path. There's no other reason.

**Comment by PhoenixIV** [comment]
https://stackoverflow.com/questions/45573065/get-relative-path-of-a-parents-subfolder

> 1. Paths starting with name of a directory or a file name are relative to **current directory**.
> 2. Paths starting with `.\` are also relative to **current directory**.
> 3. Paths starting with `..\` reference the **parent directory of current directory**.

**Comment by eibol** [comment]
You're right, I'll see to change it on next release.
Thanks.

**Comment by eibol** [comment]
This patched executable should display properly: [](https://sourceforge.net/projects/ffmpeg-batch/files/FFBatch.exe/download)

**Comment by PhoenixIV** [comment]
Yaaaay ❤❤❤
Can the `../` (folder up) path be used, too?

**Comment by eibol** [comment]
That I will assess for next release.

**Comment by PhoenixIV** [comment]
Thanks @eibol 
I was more curious about `../` than really needing it right now. Doesn't Windows take care of it?
However, thanks for the app in general, it makes life easier with my music library!

**Comment by eibol** [comment]
You're welcome. Very happy for that. 
I'm not aware of Windows handling paths with relative characters like that, It's tricky because of slight differences between ffmpeg and Windows handling paths.
