### ISSUE TITLE
"Add custom column" > "Resolution" does not work as expected

### ISSUE THREAD

**Issue by Gabriele-LS** [eibol/ffmpeg_batch#80]
Hello, I am having issues adding video width and height custom columns. First, when I add the "Resolution" columns, I also get the "Bitrate" column. Second, both the "Width" and "Height" columns show the wrong data (see image 2). I am still using version 2.8.

<img width="261" alt="CleanShot 2023-09-29 at 11 37 04@2x" src="https://github.com/eibol/ffmpeg_batch/assets/67373152/6db927c5-7c31-4957-8e5b-1fd1e0b258e3">

<img width="507" alt="CleanShot 2023-09-29 at 11 36 38@2x" src="https://github.com/eibol/ffmpeg_batch/assets/67373152/ca85ac4d-4c2b-477e-aada-20a4eb9d7109">

**Comment by eibol** [comment]
Hi, that issue was addressed in 3.0.0
