### ISSUE TITLE
Encoding statistics not displayed correctly on version 3.0

### ISSUE THREAD

**Issue by Gabriele-LS** [eibol/ffmpeg_batch#81]
Hello, I briefly tried version 3.0 and found out that the encoding statistics are not displayed correctly. I can only see the "Time elapsed."

**Comment by eibol** [comment]
Hi, I tested some encoding presets and stats work fine. Some more info, parameters used, screenshots?

**Comment by Gabriele-LS** [comment]
Hello @eibol, I reinstalled version 3.0, and the problem disappeared. I will let you know if I discover anything new about it. Thanks!
