### ISSUE TITLE
bug video encoder

### ISSUE THREAD

**Issue by chenxqiyu** [eibol/ffmpeg_batch#83]
![image](https://github.com/eibol/ffmpeg_batch/assets/10222853/4c7947f1-135e-48e9-ab1a-711a2d7ab973)
The video encoder in version 3.0.0 cannot display properly

**Comment by eibol** [comment]
Hi, that is file video codec (avc = h264).

**Comment by chenxqiyu** [comment]
> Hi, that is file video codec (avc = h264).

![image](https://github.com/eibol/ffmpeg_batch/assets/10222853/c2b11563-e402-4b0e-bc61-05024bdd86a7)
3.0.0 Display -

![image](https://github.com/eibol/ffmpeg_batch/assets/10222853/5340373c-d9f0-4e92-8d42-1245b5f4f75b)
2.8.8 Display normal

**Comment by eibol** [comment]
Hi, could you download again application and try It? I solved a language issue and re-uploaded versión 3.0.0, in SourceForge/GitHub.

**Comment by chenxqiyu** [comment]
> Hi, could you download again application and try It? I solved a language issue and re-uploaded versión 3.0.0, in SourceForge/GitHub.

Didn't see the updated version

https://github.com/eibol/ffmpeg_batch/assets/10222853/97871e7e-aec3-4044-a784-74d77f8e792a

This is the problematic test file, you can try it out

**Comment by eibol** [comment]
I could not reproduce the issue, but found a possible related but with some languages.
This [patched version](https://drive.upm.es/s/b7X1hasyM6TqiY1/download) could fix it.

**Comment by chenxqiyu** [comment]
![image](https://github.com/eibol/ffmpeg_batch/assets/10222853/6b2556ea-787d-406f-8d01-34cc873b4915)
The replacement still yields the same result

**Comment by eibol** [comment]
Unfortunately I can't replicate the issue, all works fine.
It must be something related to chinese operating system.

**Comment by eibol** [comment]
Hi, could you please try with [this patched executable ](https://drive.upm.es/s/GuYkPMtfo4bxiEC/download )for testing purposes?
Thanks
