### ISSUE TITLE
bugs about translation

### ISSUE THREAD

**Issue by bovirus** [eibol/ffmpeg_batch#86]
@eibol 

Please check latest update about resx file

**Form1.resx/Form1.it,.resx**
Lost many string (was translated in rpevious translation - not translated now).

**Form24.resx/Form24.it,.resx**
Cannot be opened by a resx translator. Syntax error.

**Form26.resx/Form26.it,.resx**
Cannot be opened by a resx translator. Syntax error.

**Comment by eibol** [comment]
I did not update some translation files in Properties folder, it is updated now.

Form1.it.resx works fine in my environment.

Regarding Form24 and Form26, they it require no resource translation, it is performed programatically.

[FFBatch.zip](https://github.com/eibol/ffmpeg_batch/files/13198797/FFBatch.zip)

**Comment by bovirus** [comment]
@eibol 

Previous language translation for Form1
![image](https://github.com/eibol/ffmpeg_batch/assets/1262554/7700771b-68e3-403f-8781-9d9cc0dd7a71)

Current Form1.it.,resx
![image](https://github.com/eibol/ffmpeg_batch/assets/1262554/c773d22f-79fa-4ad7-af6b-83fdab29cb7e)

What's happen?
Why I should re-translat what are already translated.

**Comment by eibol** [comment]
Apologize for the mistake, I've been updating Properties/translations but I forgot to download form resource files into my local workflow and overwrote it when I uploaded everything to github. Probably I should change my procedure updating code.

If you send the translated resx, I will ensure it is in my files and I'll generate an updated executable.

**Comment by bovirus** [comment]
@eibol 

The problem is only about Form1.
I will uplaod soon.

Form3/Form8 require a small update about translation but are ok (compared with previous translation).

**Comment by bovirus** [comment]
@eibol 

[Translation 2023.10.30.zip](https://github.com/eibol/ffmpeg_batch/files/13202847/Translation.2023.10.30.zip)

Italian Form1 (old version)/Form3 (updated)/Form8 (updated)

Thanks.

**Comment by eibol** [comment]
Thanks. Updated
[FFBatch_it.zip](https://github.com/eibol/ffmpeg_batch/files/13203090/FFBatch_it.zip)

**Comment by bovirus** [comment]
@eibol 

Thanks. Please close the ticket.
