### ISSUE TITLE
End of queue processing is not optimal

### ISSUE THREAD

**Issue by lchiocca** [eibol/ffmpeg_batch#88]
Hi,

First off: great piece of software. Use it all the time. Multiple thanks!
Now for the less interesting part. Over the past weeks, I've been reencoding a lot of longer video files in batches of six. It's starts off great, but when it comes to the last couple of files, it seems that the queue get confused about which video file should belong to which ffmpeg process. As an example (see screenshot): I've got 6 ffmpeg processes running but near the end the last one finished while the previous-to-last hasn't started at all and there would still be three ffmpeg processes available to convert it.
![example](https://github.com/eibol/ffmpeg_batch/assets/5980668/c99a8799-6f32-4e04-a560-e3afdc3dc8bf)

It's not a big thing - just anoying ;)

Thanks
Loris

**Comment by eibol** [comment]
Hi, thanks for the information. I'm afraid it is an undesired behaviour of the parallel encoding, it partitions all the file list in n-threads blocks, starts sequentially, but after a while it starts with the first item of every n-thread block, thus creating that annoying effect.

I have not found yet a way to solve it, it would require a complete rewriting.

By the way, [this patched version](https://sourceforge.net/projects/ffmpeg-batch/files/FFBatch.zip/download) should display Video codec column properly.

**Comment by lchiocca** [comment]
I had a quick look at the code. I haven't played around a lot with c# but from what I can tell, you are using the "Parallel.ForEach" to run the individual tasks. I think - based on microsoft examples - that you could simply create a task scheduler and pass it through the ParallelOptions. The example I found online was https://learn.microsoft.com/en-us/dotnet/api/system.threading.tasks.taskscheduler?view=net-7.0. If you look at the example it defines a LimitedConcurrencyLevelTaskScheduler that takes the maxDegreeOfParallelism as a constructor parameter. You can probably then pass a new instance of that class to the ParallelOptions.TaskScheduler and it should probably work :)

**Comment by johnloopi** [comment]
> By the way, [this patched version](https://sourceforge.net/projects/ffmpeg-batch/files/FFBatch.zip/download) should display Video codec column properly.

Thanks for that patched version, @eibol 
Will this bug be fixed in 3.0.2 or should anyone with this issue download the patched version and replace it with the one they currently have?

**Comment by eibol** [comment]
Hi, versión 3.0.2 will be released soon. Another seldom issue with columns showed up.

**Comment by eibol** [comment]
> I had a quick look at the code. I haven't played around a lot with c# but from what I can tell, you are using the "Parallel.ForEach" to run the individual tasks. I think - based on microsoft examples - that you could simply create a task scheduler and pass it through the ParallelOptions. The example I found online was https://learn.microsoft.com/en-us/dotnet/api/system.threading.tasks.taskscheduler?view=net-7.0. If you look at the example it defines a LimitedConcurrencyLevelTaskScheduler that takes the maxDegreeOfParallelism as a constructor parameter. You can probably then pass a new instance of that class to the ParallelOptions.TaskScheduler and it should probably work :)

Thanks for the suggestion. I tried the example but it is displays a compilation error.
Anyways, I've been playing with this minor annoyance and it would require a complete rewrite I cannot face, also forcing a sequential processing can slightly reduce performance. Since I'd like to keep gui part as light as possible so encoding performance is as close as command line alone, I have to keep it this way for the time being.

**Comment by eibol** [comment]
@lchiocca I've been testing some promising changes to keep multi-file encoding as ordered as possible.
If you want to try it just use this [beta version](https://drive.upm.es/s/GuYkPMtfo4bxiEC/download).

**Comment by eibol** [comment]
Also, [this beta version](https://drive.upm.es/s/GuYkPMtfo4bxiEC/download) could fix the thread lossing when reaching the end of the multi-file encoding list.
