### ISSUE TITLE
Output path buttons and behavior

### ISSUE THREAD

**Issue by PhoenixIV** [eibol/ffmpeg_batch#9]
I freak out a little because of how the output path section is behaving:
1. I cannot edit the path directly in the field
2. If I want to put an absolute path I cannot use the edit button (because it does not accept `:` and calls it "dots")
3. Using the "browse" button I can put `:`

I'd like to be able to put any value in that field by hand, no matter if relative or absolute. I don't only want to use the browse button to put a value in that field.

If it makes it easier: You could try to resolve the given path (it might not exists yet!) and hand it on to ffmpeg as absolute path.

**Comment by PhoenixIV** [comment]
One example of how the command line resolves paths:
`cd Contacts/../Contacts/../../` will go up one folder (down, up, down, up, up)

**Comment by PhoenixIV** [comment]
I suggest to remove the "edit" button next to the output path field, accept any value and parse/check that as soon as conversion starts.

**Comment by eibol** [comment]
Hi, I understand the point. However, I think many users would not understand the relative paths Windows handling. Advanced users probably would. It would also require a complete redesign of the application output path programming. I'll give a though for next release too. 

For the moment I'm trying to implement some sort of vertical resizing with some success.

**Comment by eibol** [comment]
What I may do is to make the output path field writable, so users ca write whatever they wish, at their own risk, but keeping the buttons for basic users.

**Comment by eibol** [comment]
Hi, in this executable you write directly on output path. Relative paths for the moment behave the same.
I have also added some resizing to the application, it can now be maximized.
https://sourceforge.net/projects/ffmpeg-batch/files/FFBatch.exe/download
