### ISSUE TITLE
'analyzeduration' and 'probesize'?

### ISSUE THREAD

**Issue by 6GNerd** [eibol/ffmpeg_batch#90]
I can't encode movies. This error is popping up. Where can I find the settings to change 'analyeduration' and 'probesize'
![image](https://github.com/eibol/ffmpeg_batch/assets/147439827/07c7b9c2-1bdb-49c5-8af2-a697cb723032)

And how to workaround the subtitle mishap?

Thanks for the amazing software.

**Comment by eibol** [comment]
Hi, please try removing -map 0, it seems that the input file has a subtitle stream format not compatible with output format.
