### ISSUE TITLE
Language files Strings2 request or not

### ISSUE THREAD

**Issue by bovirus** [eibol/ffmpeg_batch#93]
@eibol 

About this language file

Strings2.res 

file why only tehse languages availbel (and not other)

Strings2.ar-EG.resx
Strings2.es.resx

Is it necessary the Strings2.resx file group?

Thanks.

**Comment by eibol** [comment]
All Strings2 res files were merged into Strings, should have done it before.
You can safely remove all strings2 files.

**Comment by bovirus** [comment]
@eilbol

Please remove strings2 resources for repostiory.
Thanks.-

**Comment by eibol** [comment]
Done. Thanks
