### ISSUE TITLE
Burn subtitle from source file not working since 3.0.1

### ISSUE THREAD

**Issue by ClaudioMixDDR** [eibol/ffmpeg_batch#94]
Up to version 3.0.0 it works without problems, but since 3.0.1 it fails when trying to burn a subtitle from the source file.
I tried changing to another ffmpeg compilation but the same thing happens, I think the "%ff" parameter is not delivering the path correctly.

Example parameter:

-c:v libx264 -crf 23 -vf "subtitles=%ff:stream_index=0" -c:a copy -sn

The error is the following:

[Parsed_subtitles_0 @ 000001ec0b5a0f00] Unable to open 01.mkv
[AVFilterGraph @ 000001ec086a6dc0] Error initializing filters
[vost#0:0/libx264 @ 000001ec0aafb940] Error initializing a simple filtergraph

Thank you very much in advance for your great work with this app.

**Comment by eibol** [comment]
Hi, I have yet to find a way to escape characters in Windows to make variables work inside and outside af/vf filters.

**Comment by eibol** [comment]
I've added new variables for the filter case, you can try this [patched version ](https://drive.upm.es/s/F9B4VJ68BcaqV4F/download) replacing your current one. 

In main tab, using %f1 variable.  (fx button at parameters should display the new variable settings).

You can also use a new feature in Subtitles tab for the same purpose, after Burn subtitles checkmark (use input file subtitles).

**Comment by ClaudioMixDDR** [comment]
Thank you so much!
Works fine with %f1

**Comment by ClaudioMixDDR** [comment]
Hello again!
Forgot to try something :(

This verification is not being performed when using the new variable %f1.

![image](https://github.com/eibol/ffmpeg_batch/assets/60362931/ad233e45-a5b4-404b-b834-d373ee702a7c)

**Comment by eibol** [comment]
Hi, thanks for the report, this [patched version](https://drive.upm.es/s/F9B4VJ68BcaqV4F/download) should do it right.

**Comment by ClaudioMixDDR** [comment]
Now it works, I can convert everything without problems.
