### ISSUE TITLE
checksum problem with 3.0.3

### ISSUE THREAD

**Issue by UnidentifiedTag** [eibol/ffmpeg_batch#95]
both the github download and sourceforge download come out with a checksum error for me

![Screenshot 2024-01-10 114157](https://github.com/eibol/ffmpeg_batch/assets/54625394/7ba5e98a-22d0-4f53-a1fc-f9c803ee97f1)

**Comment by eibol** [comment]
I have downloaded the installer and I find no issue like that.
The md5 checksum file could not be copied for some reason. If you did not change ffmpeg.exe you can Trust current ffmpeg
and go ahead.

**Comment by UnidentifiedTag** [comment]
could you give me the checksum code for this one?

**Comment by eibol** [comment]
It is correct: 827da3e84b02b8cfc33d1d80815bb3f2
