### ISSUE TITLE
Improve night mode

### ISSUE THREAD

**Issue by opusforlife2** [eibol/ffmpeg_batch#97]
Hi. When using night mode, a bunch of stuff in the GUI is still white or another very light colour, which contrasts horribly with the overall dark colour and puts a strain on the eyes.

Could the light colours be replaced? If not, then could the contrast be reduced to make the night mode usable at least?

**Comment by eibol** [comment]
Hi, I'll search all application windows for pending night mode implementations.
Could you provide some examples?

**Comment by eibol** [comment]
Hi, I've included a workaround for the startap "white flash", you can also disable the table gridlines in the context menu.
Other thigs require some additional work.

The controls redrawing is a consequence of packing so much controls in the main form, which does not use video acceleration,
at this point not much can be done. I hope it improves with these changes.

[FFBatch.zip](https://github.com/eibol/ffmpeg_batch/files/13992940/FFBatch.zip)
