### ISSUE TITLE
Is there any way to keep ffmpeg.exe outside of the ffmpeg_batch folder?

### ISSUE THREAD

**Issue by dr04e606** [eibol/ffmpeg_batch#98]
When launched for the first time, FFBatch prompts you to either download ffmpeg, or open a location on your computer where you have it stored. 

To my surprise, opening an existing location with ffmpeg.exe, creates a copy of it in the FFBatch folder. 
Is there any way I can just specify and existing location outside the FFBatch folder and not have it copied in there?

**Comment by eibol** [comment]
For the moment ffmpeg.exe is always expected to be in the application folder, maybe in the future.

**Comment by dr04e606** [comment]
Got it! Thanks!

In any case, FFBatch is by far the best FFmpeg GUI (at least for my needs) that I've ever tried. 
Thank you for creating and maintaining it!

**Comment by longwu9t** [comment]
add ffmpeg(shared not static) folder to your syspath
mklink yourpath\ffmpeg.exe ffbatch\ffmpeg.exe
OR
copy ffmpeg.exe(only the exe) to ffbatch's folder

**Comment by eibol** [comment]
This [beta release](https://drive.upm.es/s/PV26uIpHt0WPd6I/download) allows ffmpeg.exe outside application path. It supports shared ffmpeg two.
