### ISSUE TITLE
Multi-Line Parameters generate an Error

### ISSUE THREAD

**Issue by Mae72DE** [eibol/ffmpeg_batch#99]
Why I like to use Parameters in multiple lines?<br>
I think it's better to read - and a commentary-function would be nice …

```
ffmpeg
 -i "Hörbuch"                      # Quelle
  -af "                            # Begin des Audio Filters
    asendcmd=0.0 afftdn sn start,  # Audio:SendCommand: SampleNoise capture
    asendcmd=0.4 afftdn sn stop,   # 0,4 Sek. Ende des Captures
    adeclick                       # Audio:Declicker   ( Falls von Schaltplatte aufgenommen)
    afftdn=nr=20:nf=-40            # Audio:Fast Fourier Transform DeNoise
   "                               # Audio-Filter end
  -ac 1                            # Audio:Channel 1 (Mono)  (MP3 Player besitzt nur einen Lautsprecher)
  -ar 16k                          # Audio:Rate (Abtastfrequenz): 16 kHz  (Aufnahmen Teilweise von Audiokassette)
 "Ausgabe\Hörbuch.mp3"             # Ausgabe-Datei
```

But if you try that it miss - even you find the lost comma after adeclick, …
It would be nice to have the option to put every "command" in a new line, and add some # comments at the end.
And a special Comment-Out Function ☒/☑ to begin of every line to just chance these settings.

**Comment by eibol** [comment]
I see the point of the suggestion. Parameters field was never intended to include descriptions, source and destination file are not to be included. I would try using preset description as much as possible, maybe in the future this feature is possible.
